<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/07/02 10:58:58

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'pgsql:dbname=agilhu;host=localhost',
  'username' => 'agilhu',
  'password' => 'agilhu',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
