<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/07/02 11:44:03
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
