<?php
// auto-generated by sfViewConfigHandler
// date: 2010/07/02 10:58:59
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (!is_null($layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout')))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (is_null($this->getDecoratorTemplate()) && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Uso de proyectos', false, false);
  $response->addMeta('description', 'Los usuarios escojen sus respectivos proyectos y los manejan', false, false);
  $response->addMeta('keywords', 'proyecto, gestion,historias,modulos', false, false);
  $response->addMeta('language', 'es', false, false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('extjs/resources/css/ext-all.css', '', array ());
  $response->addStylesheet('extjs/resources/css/xtheme-blue.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('file-upload.css', '', array ());
  $response->addStylesheet('example.css', '', array ());
  $response->addStylesheet('Spotlight.css', '', array ());
  $response->addStylesheet('Spinner.css', '', array ());
  $response->addStylesheet('Ext.ux.form.LovCombo.css', '', array ());
  $response->addStylesheet('lovcombo.css', '', array ());
  $response->addStylesheet('GroupSummary.css', '', array ());
  $response->addStylesheet('treegrid.css', '', array ());
  $response->addJavascript('http://www.google.com/jsapi', '', array ());
  $response->addJavascript('extjs/adapter/ext/ext-base.js', '', array ());
  $response->addJavascript('extjs/ext-all.js', '', array ());
  $response->addJavascript('extjs/src/locale/ext-lang-es.js', '', array ());
  $response->addJavascript('usuario/actualizarDatos.js', '', array ());
  $response->addJavascript('usuario/actualizarClave.js', '', array ());
  $response->addJavascript('principal/principal.js', '', array ());
  $response->addJavascript('aux/Ext.ux.grid.Search.js', '', array ());
  $response->addJavascript('aux/funciones.js', '', array ());
  $response->addJavascript('proyecto/proyecto.js', '', array ());
  $response->addJavascript('proyecto/invitaciones.js', '', array ());
  $response->addJavascript('documento/documentos.js', '', array ());
  $response->addJavascript('aux/FileUploadField.js', '', array ());
  $response->addJavascript('aux/example.js', '', array ());
  $response->addJavascript('modulo/modulo.js', '', array ());
  $response->addJavascript('proyecto/listaProyecto.js', '', array ());
  $response->addJavascript('HU/historiaUsuario.js', '', array ());
  $response->addJavascript('aux/Ext.ux.grid.RowExpander.js', '', array ());
  $response->addJavascript('participante/participante.js', '', array ());
  $response->addJavascript('participante/mensaje.js', '', array ());
  $response->addJavascript('aux/Spotlight.js', '', array ());
  $response->addJavascript('PruebaExperto/pruebaHistoria.js', '', array ());
  $response->addJavascript('Spinner/Spinner.js', '', array ());
  $response->addJavascript('Spinner/SpinnerField.js', '', array ());
  $response->addJavascript('aux/Ext.ux.form.LovCombo.js', '', array ());
  $response->addJavascript('proyecto/datosProyecto.js', '', array ());
  $response->addJavascript('reporte/reportes.js', '', array ());
  $response->addJavascript('aux/GroupSummary.js', '', array ());
  $response->addJavascript('aux/TreeGridSorter.js', '', array ());
  $response->addJavascript('aux/TreeGridColumnResizer.js', '', array ());
  $response->addJavascript('aux/TreeGridNodeUI.js', '', array ());
  $response->addJavascript('aux/TreeGridLoader.js', '', array ());
  $response->addJavascript('aux/TreeGridColumns.js', '', array ());
  $response->addJavascript('aux/TreeGrid.js', '', array ());


