<?php


/**
 * This class adds structure of 'agilhu_proyecto' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Jun 28 16:09:55 2010
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class AgilhuProyectoMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.AgilhuProyectoMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(AgilhuProyectoPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(AgilhuProyectoPeer::TABLE_NAME);
		$tMap->setPhpName('AgilhuProyecto');
		$tMap->setClassname('AgilhuProyecto');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('agilhu_proyecto_pro_id_seq');

		$tMap->addPrimaryKey('PRO_ID', 'ProId', 'INTEGER', true, null);

		$tMap->addForeignKey('USU_ID', 'UsuId', 'INTEGER', 'agilhu_usuario', 'USU_ID', false, null);

		$tMap->addColumn('PRO_NOMBRE_CORTO', 'ProNombreCorto', 'VARCHAR', false, 80);

		$tMap->addColumn('PRO_NOMBRE', 'ProNombre', 'VARCHAR', false, 300);

		$tMap->addColumn('PRO_AREA_APLICACION', 'ProAreaAplicacion', 'VARCHAR', false, 500);

		$tMap->addColumn('PRO_FECHA_INICIO', 'ProFechaInicio', 'DATE', false, null);

		$tMap->addColumn('PRO_FECHA_FINALIZACION', 'ProFechaFinalizacion', 'DATE', false, null);

		$tMap->addColumn('PRO_ESTADO', 'ProEstado', 'VARCHAR', false, 50);

		$tMap->addColumn('PRO_LOGO', 'ProLogo', 'VARCHAR', false, 500);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('PRO_DESCRIPCION', 'ProDescripcion', 'LONGVARCHAR', false, null);

	} // doBuild()

} // AgilhuProyectoMapBuilder
