<?php


/**
 * This class adds structure of 'agilhu_documento' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Aug 30 10:19:33 2010
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class AgilhuDocumentoMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.AgilhuDocumentoMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(AgilhuDocumentoPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(AgilhuDocumentoPeer::TABLE_NAME);
		$tMap->setPhpName('AgilhuDocumento');
		$tMap->setClassname('AgilhuDocumento');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('agilhu_documento_doc_id_seq');

		$tMap->addPrimaryKey('DOC_ID', 'DocId', 'INTEGER', true, null);

		$tMap->addColumn('DOC_NOMBRE', 'DocNombre', 'VARCHAR', false, 200);

		$tMap->addColumn('DOC_DESCRIPCION', 'DocDescripcion', 'VARCHAR', false, 1000);

		$tMap->addColumn('DOC_TAMANO', 'DocTamano', 'VARCHAR', false, 100);

		$tMap->addColumn('DOC_TIPO', 'DocTipo', 'VARCHAR', false, 200);

		$tMap->addColumn('DOC_CONTENIDO', 'DocContenido', 'BLOB', false, null);

		$tMap->addColumn('DOC_ID_PRO', 'DocIdPro', 'INTEGER', false, null);

		$tMap->addColumn('DOC_ID_MOD', 'DocIdMod', 'INTEGER', false, null);

		$tMap->addColumn('DOC_ID_HIS', 'DocIdHis', 'INTEGER', false, null);

		$tMap->addColumn('DOC_ID_REMITENTE', 'DocIdRemitente', 'INTEGER', false, null);

		$tMap->addColumn('DOC_VISIBILIDAD', 'DocVisibilidad', 'VARCHAR', false, 20);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

	} // doBuild()

} // AgilhuDocumentoMapBuilder
