<?php


/**
 * This class adds structure of 'agilhu_preguntas' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Jun 28 16:09:55 2010
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class AgilhuPreguntasMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.AgilhuPreguntasMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(AgilhuPreguntasPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(AgilhuPreguntasPeer::TABLE_NAME);
		$tMap->setPhpName('AgilhuPreguntas');
		$tMap->setClassname('AgilhuPreguntas');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('agilhu_preguntas_pre_id_seq');

		$tMap->addPrimaryKey('PRE_ID', 'PreId', 'INTEGER', true, null);

		$tMap->addForeignKey('PRE_PRO_ID', 'PreProId', 'INTEGER', 'agilhu_proyecto', 'PRO_ID', false, null);

		$tMap->addColumn('PRE_DESCRIPCION', 'PreDescripcion', 'VARCHAR', true, 1000);

		$tMap->addColumn('PRE_CARACTERISTICA_CALIDAD', 'PreCaracteristicaCalidad', 'VARCHAR', false, 100);

		$tMap->addColumn('PRE_CATEGORIA', 'PreCategoria', 'VARCHAR', false, 200);

	} // doBuild()

} // AgilhuPreguntasMapBuilder
