<?php


/**
 * This class adds structure of 'agilhu_mensaje_recibido' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Jun 28 16:09:55 2010
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class AgilhuMensajeRecibidoMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.AgilhuMensajeRecibidoMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(AgilhuMensajeRecibidoPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(AgilhuMensajeRecibidoPeer::TABLE_NAME);
		$tMap->setPhpName('AgilhuMensajeRecibido');
		$tMap->setClassname('AgilhuMensajeRecibido');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('agilhu_mensaje_recibido_men_id_seq');

		$tMap->addPrimaryKey('MEN_ID', 'MenId', 'INTEGER', true, null);

		$tMap->addColumn('MEN_PRO_ID', 'MenProId', 'INTEGER', false, null);

		$tMap->addColumn('MEN_DE', 'MenDe', 'VARCHAR', false, 250);

		$tMap->addColumn('MEN_PARA', 'MenPara', 'VARCHAR', false, 250);

		$tMap->addColumn('MEN_ASUNTO', 'MenAsunto', 'VARCHAR', false, 250);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'DATE', false, null);

		$tMap->addColumn('MEN_MENSAJE', 'MenMensaje', 'VARCHAR', false, 250);

	} // doBuild()

} // AgilhuMensajeRecibidoMapBuilder
