<?php


/**
 * This class adds structure of 'agilhu_rol_proyecto' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Jun 28 16:09:56 2010
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class AgilhuRolProyectoMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.AgilhuRolProyectoMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(AgilhuRolProyectoPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(AgilhuRolProyectoPeer::TABLE_NAME);
		$tMap->setPhpName('AgilhuRolProyecto');
		$tMap->setClassname('AgilhuRolProyecto');

		$tMap->setUseIdGenerator(false);

		$tMap->addPrimaryKey('ROP_ID', 'RopId', 'INTEGER', true, null);

		$tMap->addColumn('ROP_NOMBRE', 'RopNombre', 'VARCHAR', true, 50);

		$tMap->addColumn('ROP_DESCIPCION', 'RopDescipcion', 'VARCHAR', false, 100);

	} // doBuild()

} // AgilhuRolProyectoMapBuilder
