<?php


/**
 * This class adds structure of 'agilhu_modulo' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Jun 28 16:09:55 2010
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class AgilhuModuloMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.AgilhuModuloMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(AgilhuModuloPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(AgilhuModuloPeer::TABLE_NAME);
		$tMap->setPhpName('AgilhuModulo');
		$tMap->setClassname('AgilhuModulo');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('agilhu_modulo_mod_id_seq');

		$tMap->addPrimaryKey('MOD_ID', 'ModId', 'INTEGER', true, null);

		$tMap->addForeignKey('PRO_ID', 'ProId', 'INTEGER', 'agilhu_proyecto', 'PRO_ID', false, null);

		$tMap->addColumn('MOD_NOMBRE', 'ModNombre', 'VARCHAR', false, 150);

		$tMap->addColumn('MOD_ESTADO', 'ModEstado', 'VARCHAR', false, 80);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('MOD_DESCRIPCION', 'ModDescripcion', 'LONGVARCHAR', false, null);

		$tMap->addColumn('MOD_PADRE', 'ModPadre', 'INTEGER', false, null);

		$tMap->addColumn('MOD_HABILITADO', 'ModHabilitado', 'VARCHAR', false, 20);

	} // doBuild()

} // AgilhuModuloMapBuilder
