<?php


/**
 * This class adds structure of 'aguilhu_rol' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Thu Nov 19 11:56:14 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class AguilhuRolMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.AguilhuRolMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(AguilhuRolPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(AguilhuRolPeer::TABLE_NAME);
		$tMap->setPhpName('AguilhuRol');
		$tMap->setClassname('AguilhuRol');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('aguilhu_rol_rol_id_seq');

		$tMap->addPrimaryKey('ROL_ID', 'RolId', 'INTEGER', true, null);

		$tMap->addColumn('ROL_NAME', 'RolName', 'VARCHAR', true, 50);

	} // doBuild()

} // AguilhuRolMapBuilder
