<?php


/**
 * This class adds structure of 'chat' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Jun 28 16:09:56 2010
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ChatMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ChatMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(ChatPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(ChatPeer::TABLE_NAME);
		$tMap->setPhpName('Chat');
		$tMap->setClassname('Chat');

		$tMap->setUseIdGenerator(true);

		$tMap->setPrimaryKeyMethodInfo('chat_id_seq');

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('DE', 'De', 'VARCHAR', true, 255);

		$tMap->addColumn('PARA', 'Para', 'VARCHAR', true, 255);

		$tMap->addColumn('MESSAGE', 'Message', 'LONGVARCHAR', true, null);

		$tMap->addColumn('SENT', 'Sent', 'TIMESTAMP', true, null);

		$tMap->addColumn('RECD', 'Recd', 'INTEGER', true, null);

	} // doBuild()

} // ChatMapBuilder
