<?php


/**
 * This class adds structure of 'gen_usuario' table to 'agilhu' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sat Oct 17 12:30:28 2009
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class UsuarioMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.UsuarioMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(UsuarioPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(UsuarioPeer::TABLE_NAME);
		$tMap->setPhpName('Usuario');
		$tMap->setClassname('Usuario');

		$tMap->setUseIdGenerator(false);

		$tMap->addPrimaryKey('ID_USUARIO', 'IdUsuario', 'INTEGER', true, null);

		$tMap->addColumn('USU_USUARIO', 'UsuUsuario', 'VARCHAR', true, 30);

		$tMap->addColumn('USU_CLAVE', 'UsuClave', 'VARCHAR', true, 32);

		$tMap->addColumn('USU_NOMBRES', 'UsuNombres', 'VARCHAR', true, 50);

		$tMap->addColumn('USU_APELLIDOS', 'UsuApellidos', 'VARCHAR', true, 50);

		$tMap->addColumn('USU_CORREO', 'UsuCorreo', 'VARCHAR', true, 50);

		$tMap->addForeignKey('USU_ROL_ID', 'UsuRolId', 'INTEGER', 'gen_rol', 'ROL_ID', false, null);

		$tMap->addColumn('USU_ESTADO', 'UsuEstado', 'BOOLEAN', true, null);

	} // doBuild()

} // UsuarioMapBuilder
