<?php

/**
 * Base class that represents a row from the 'agilhu_documento' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Aug 30 10:19:33 2010
 *
 * @package    lib.model.om
 */
abstract class BaseAgilhuDocumento extends BaseObject  implements Persistent {


  const PEER = 'AgilhuDocumentoPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        AgilhuDocumentoPeer
	 */
	protected static $peer;

	/**
	 * The value for the doc_id field.
	 * @var        int
	 */
	protected $doc_id;

	/**
	 * The value for the doc_nombre field.
	 * @var        string
	 */
	protected $doc_nombre;

	/**
	 * The value for the doc_descripcion field.
	 * @var        string
	 */
	protected $doc_descripcion;

	/**
	 * The value for the doc_tamano field.
	 * @var        string
	 */
	protected $doc_tamano;

	/**
	 * The value for the doc_tipo field.
	 * @var        string
	 */
	protected $doc_tipo;

	/**
	 * The value for the doc_contenido field.
	 * @var        resource
	 */
	protected $doc_contenido;

	/**
	 * The value for the doc_id_pro field.
	 * @var        int
	 */
	protected $doc_id_pro;

	/**
	 * The value for the doc_id_mod field.
	 * @var        int
	 */
	protected $doc_id_mod;

	/**
	 * The value for the doc_id_his field.
	 * @var        int
	 */
	protected $doc_id_his;

	/**
	 * The value for the doc_id_remitente field.
	 * @var        int
	 */
	protected $doc_id_remitente;

	/**
	 * The value for the doc_visibilidad field.
	 * @var        string
	 */
	protected $doc_visibilidad;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseAgilhuDocumento object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [doc_id] column value.
	 * 
	 * @return     int
	 */
	public function getDocId()
	{
		return $this->doc_id;
	}

	/**
	 * Get the [doc_nombre] column value.
	 * 
	 * @return     string
	 */
	public function getDocNombre()
	{
		return $this->doc_nombre;
	}

	/**
	 * Get the [doc_descripcion] column value.
	 * 
	 * @return     string
	 */
	public function getDocDescripcion()
	{
		return $this->doc_descripcion;
	}

	/**
	 * Get the [doc_tamano] column value.
	 * 
	 * @return     string
	 */
	public function getDocTamano()
	{
		return $this->doc_tamano;
	}

	/**
	 * Get the [doc_tipo] column value.
	 * 
	 * @return     string
	 */
	public function getDocTipo()
	{
		return $this->doc_tipo;
	}

	/**
	 * Get the [doc_contenido] column value.
	 * 
	 * @return     resource
	 */
	public function getDocContenido()
	{
		return $this->doc_contenido;
	}

	/**
	 * Get the [doc_id_pro] column value.
	 * 
	 * @return     int
	 */
	public function getDocIdPro()
	{
		return $this->doc_id_pro;
	}

	/**
	 * Get the [doc_id_mod] column value.
	 * 
	 * @return     int
	 */
	public function getDocIdMod()
	{
		return $this->doc_id_mod;
	}

	/**
	 * Get the [doc_id_his] column value.
	 * 
	 * @return     int
	 */
	public function getDocIdHis()
	{
		return $this->doc_id_his;
	}

	/**
	 * Get the [doc_id_remitente] column value.
	 * 
	 * @return     int
	 */
	public function getDocIdRemitente()
	{
		return $this->doc_id_remitente;
	}

	/**
	 * Get the [doc_visibilidad] column value.
	 * 
	 * @return     string
	 */
	public function getDocVisibilidad()
	{
		return $this->doc_visibilidad;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->created_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [doc_id] column.
	 * 
	 * @param      int $v new value
	 * @return     AgilhuDocumento The current object (for fluent API support)
	 */
	public function setDocId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->doc_id !== $v) {
			$this->doc_id = $v;
			$this->modifiedColumns[] = AgilhuDocumentoPeer::DOC_ID;
		}

		return $this;
	} // setDocId()

	/**
	 * Set the value of [doc_nombre] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuDocumento The current object (for fluent API support)
	 */
	public function setDocNombre($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->doc_nombre !== $v) {
			$this->doc_nombre = $v;
			$this->modifiedColumns[] = AgilhuDocumentoPeer::DOC_NOMBRE;
		}

		return $this;
	} // setDocNombre()

	/**
	 * Set the value of [doc_descripcion] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuDocumento The current object (for fluent API support)
	 */
	public function setDocDescripcion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->doc_descripcion !== $v) {
			$this->doc_descripcion = $v;
			$this->modifiedColumns[] = AgilhuDocumentoPeer::DOC_DESCRIPCION;
		}

		return $this;
	} // setDocDescripcion()

	/**
	 * Set the value of [doc_tamano] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuDocumento The current object (for fluent API support)
	 */
	public function setDocTamano($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->doc_tamano !== $v) {
			$this->doc_tamano = $v;
			$this->modifiedColumns[] = AgilhuDocumentoPeer::DOC_TAMANO;
		}

		return $this;
	} // setDocTamano()

	/**
	 * Set the value of [doc_tipo] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuDocumento The current object (for fluent API support)
	 */
	public function setDocTipo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->doc_tipo !== $v) {
			$this->doc_tipo = $v;
			$this->modifiedColumns[] = AgilhuDocumentoPeer::DOC_TIPO;
		}

		return $this;
	} // setDocTipo()

	/**
	 * Set the value of [doc_contenido] column.
	 * 
	 * @param      resource $v new value
	 * @return     AgilhuDocumento The current object (for fluent API support)
	 */
	public function setDocContenido($v)
	{
		// Because BLOB columns are streams in PDO we have to assume that they are
		// always modified when a new value is passed in.  For example, the contents
		// of the stream itself may have changed externally.
		if (!is_resource($v)) {
			$this->doc_contenido = fopen('php://memory', 'r+');
			fwrite($this->doc_contenido, $v);
			rewind($this->doc_contenido);
		} else { // it's already a stream
			$this->doc_contenido = $v;
		}
		$this->modifiedColumns[] = AgilhuDocumentoPeer::DOC_CONTENIDO;

		return $this;
	} // setDocContenido()

	/**
	 * Set the value of [doc_id_pro] column.
	 * 
	 * @param      int $v new value
	 * @return     AgilhuDocumento The current object (for fluent API support)
	 */
	public function setDocIdPro($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->doc_id_pro !== $v) {
			$this->doc_id_pro = $v;
			$this->modifiedColumns[] = AgilhuDocumentoPeer::DOC_ID_PRO;
		}

		return $this;
	} // setDocIdPro()

	/**
	 * Set the value of [doc_id_mod] column.
	 * 
	 * @param      int $v new value
	 * @return     AgilhuDocumento The current object (for fluent API support)
	 */
	public function setDocIdMod($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->doc_id_mod !== $v) {
			$this->doc_id_mod = $v;
			$this->modifiedColumns[] = AgilhuDocumentoPeer::DOC_ID_MOD;
		}

		return $this;
	} // setDocIdMod()

	/**
	 * Set the value of [doc_id_his] column.
	 * 
	 * @param      int $v new value
	 * @return     AgilhuDocumento The current object (for fluent API support)
	 */
	public function setDocIdHis($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->doc_id_his !== $v) {
			$this->doc_id_his = $v;
			$this->modifiedColumns[] = AgilhuDocumentoPeer::DOC_ID_HIS;
		}

		return $this;
	} // setDocIdHis()

	/**
	 * Set the value of [doc_id_remitente] column.
	 * 
	 * @param      int $v new value
	 * @return     AgilhuDocumento The current object (for fluent API support)
	 */
	public function setDocIdRemitente($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->doc_id_remitente !== $v) {
			$this->doc_id_remitente = $v;
			$this->modifiedColumns[] = AgilhuDocumentoPeer::DOC_ID_REMITENTE;
		}

		return $this;
	} // setDocIdRemitente()

	/**
	 * Set the value of [doc_visibilidad] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuDocumento The current object (for fluent API support)
	 */
	public function setDocVisibilidad($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->doc_visibilidad !== $v) {
			$this->doc_visibilidad = $v;
			$this->modifiedColumns[] = AgilhuDocumentoPeer::DOC_VISIBILIDAD;
		}

		return $this;
	} // setDocVisibilidad()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     AgilhuDocumento The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = AgilhuDocumentoPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->doc_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->doc_nombre = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->doc_descripcion = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->doc_tamano = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->doc_tipo = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->doc_contenido = $row[$startcol + 5];
			$this->doc_id_pro = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->doc_id_mod = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->doc_id_his = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->doc_id_remitente = ($row[$startcol + 9] !== null) ? (int) $row[$startcol + 9] : null;
			$this->doc_visibilidad = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->created_at = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 12; // 12 = AgilhuDocumentoPeer::NUM_COLUMNS - AgilhuDocumentoPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating AgilhuDocumento object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AgilhuDocumentoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = AgilhuDocumentoPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseAgilhuDocumento:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AgilhuDocumentoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			AgilhuDocumentoPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseAgilhuDocumento:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseAgilhuDocumento:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(AgilhuDocumentoPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AgilhuDocumentoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseAgilhuDocumento:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			AgilhuDocumentoPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = AgilhuDocumentoPeer::DOC_ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = AgilhuDocumentoPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setDocId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += AgilhuDocumentoPeer::doUpdate($this, $con);
				}

				// Rewind the doc_contenido LOB column, since PDO does not rewind after inserting value.
				if ($this->doc_contenido !== null && is_resource($this->doc_contenido)) {
					rewind($this->doc_contenido);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = AgilhuDocumentoPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AgilhuDocumentoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getDocId();
				break;
			case 1:
				return $this->getDocNombre();
				break;
			case 2:
				return $this->getDocDescripcion();
				break;
			case 3:
				return $this->getDocTamano();
				break;
			case 4:
				return $this->getDocTipo();
				break;
			case 5:
				return $this->getDocContenido();
				break;
			case 6:
				return $this->getDocIdPro();
				break;
			case 7:
				return $this->getDocIdMod();
				break;
			case 8:
				return $this->getDocIdHis();
				break;
			case 9:
				return $this->getDocIdRemitente();
				break;
			case 10:
				return $this->getDocVisibilidad();
				break;
			case 11:
				return $this->getCreatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = AgilhuDocumentoPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getDocId(),
			$keys[1] => $this->getDocNombre(),
			$keys[2] => $this->getDocDescripcion(),
			$keys[3] => $this->getDocTamano(),
			$keys[4] => $this->getDocTipo(),
			$keys[5] => $this->getDocContenido(),
			$keys[6] => $this->getDocIdPro(),
			$keys[7] => $this->getDocIdMod(),
			$keys[8] => $this->getDocIdHis(),
			$keys[9] => $this->getDocIdRemitente(),
			$keys[10] => $this->getDocVisibilidad(),
			$keys[11] => $this->getCreatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AgilhuDocumentoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setDocId($value);
				break;
			case 1:
				$this->setDocNombre($value);
				break;
			case 2:
				$this->setDocDescripcion($value);
				break;
			case 3:
				$this->setDocTamano($value);
				break;
			case 4:
				$this->setDocTipo($value);
				break;
			case 5:
				$this->setDocContenido($value);
				break;
			case 6:
				$this->setDocIdPro($value);
				break;
			case 7:
				$this->setDocIdMod($value);
				break;
			case 8:
				$this->setDocIdHis($value);
				break;
			case 9:
				$this->setDocIdRemitente($value);
				break;
			case 10:
				$this->setDocVisibilidad($value);
				break;
			case 11:
				$this->setCreatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = AgilhuDocumentoPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setDocId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setDocNombre($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setDocDescripcion($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setDocTamano($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setDocTipo($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setDocContenido($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setDocIdPro($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setDocIdMod($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setDocIdHis($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setDocIdRemitente($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setDocVisibilidad($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setCreatedAt($arr[$keys[11]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(AgilhuDocumentoPeer::DATABASE_NAME);

		if ($this->isColumnModified(AgilhuDocumentoPeer::DOC_ID)) $criteria->add(AgilhuDocumentoPeer::DOC_ID, $this->doc_id);
		if ($this->isColumnModified(AgilhuDocumentoPeer::DOC_NOMBRE)) $criteria->add(AgilhuDocumentoPeer::DOC_NOMBRE, $this->doc_nombre);
		if ($this->isColumnModified(AgilhuDocumentoPeer::DOC_DESCRIPCION)) $criteria->add(AgilhuDocumentoPeer::DOC_DESCRIPCION, $this->doc_descripcion);
		if ($this->isColumnModified(AgilhuDocumentoPeer::DOC_TAMANO)) $criteria->add(AgilhuDocumentoPeer::DOC_TAMANO, $this->doc_tamano);
		if ($this->isColumnModified(AgilhuDocumentoPeer::DOC_TIPO)) $criteria->add(AgilhuDocumentoPeer::DOC_TIPO, $this->doc_tipo);
		if ($this->isColumnModified(AgilhuDocumentoPeer::DOC_CONTENIDO)) $criteria->add(AgilhuDocumentoPeer::DOC_CONTENIDO, $this->doc_contenido);
		if ($this->isColumnModified(AgilhuDocumentoPeer::DOC_ID_PRO)) $criteria->add(AgilhuDocumentoPeer::DOC_ID_PRO, $this->doc_id_pro);
		if ($this->isColumnModified(AgilhuDocumentoPeer::DOC_ID_MOD)) $criteria->add(AgilhuDocumentoPeer::DOC_ID_MOD, $this->doc_id_mod);
		if ($this->isColumnModified(AgilhuDocumentoPeer::DOC_ID_HIS)) $criteria->add(AgilhuDocumentoPeer::DOC_ID_HIS, $this->doc_id_his);
		if ($this->isColumnModified(AgilhuDocumentoPeer::DOC_ID_REMITENTE)) $criteria->add(AgilhuDocumentoPeer::DOC_ID_REMITENTE, $this->doc_id_remitente);
		if ($this->isColumnModified(AgilhuDocumentoPeer::DOC_VISIBILIDAD)) $criteria->add(AgilhuDocumentoPeer::DOC_VISIBILIDAD, $this->doc_visibilidad);
		if ($this->isColumnModified(AgilhuDocumentoPeer::CREATED_AT)) $criteria->add(AgilhuDocumentoPeer::CREATED_AT, $this->created_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(AgilhuDocumentoPeer::DATABASE_NAME);

		$criteria->add(AgilhuDocumentoPeer::DOC_ID, $this->doc_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getDocId();
	}

	/**
	 * Generic method to set the primary key (doc_id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setDocId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of AgilhuDocumento (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setDocNombre($this->doc_nombre);

		$copyObj->setDocDescripcion($this->doc_descripcion);

		$copyObj->setDocTamano($this->doc_tamano);

		$copyObj->setDocTipo($this->doc_tipo);

		$copyObj->setDocContenido($this->doc_contenido);

		$copyObj->setDocIdPro($this->doc_id_pro);

		$copyObj->setDocIdMod($this->doc_id_mod);

		$copyObj->setDocIdHis($this->doc_id_his);

		$copyObj->setDocIdRemitente($this->doc_id_remitente);

		$copyObj->setDocVisibilidad($this->doc_visibilidad);

		$copyObj->setCreatedAt($this->created_at);


		$copyObj->setNew(true);

		$copyObj->setDocId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     AgilhuDocumento Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     AgilhuDocumentoPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new AgilhuDocumentoPeer();
		}
		return self::$peer;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseAgilhuDocumento:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseAgilhuDocumento::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseAgilhuDocumento
