<?php

/**
 * Base class that represents a row from the 'agilhu_proyecto' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Aug 30 10:19:34 2010
 *
 * @package    lib.model.om
 */
abstract class BaseAgilhuProyecto extends BaseObject  implements Persistent {


  const PEER = 'AgilhuProyectoPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        AgilhuProyectoPeer
	 */
	protected static $peer;

	/**
	 * The value for the pro_id field.
	 * @var        int
	 */
	protected $pro_id;

	/**
	 * The value for the usu_id field.
	 * @var        int
	 */
	protected $usu_id;

	/**
	 * The value for the pro_nombre_corto field.
	 * @var        string
	 */
	protected $pro_nombre_corto;

	/**
	 * The value for the pro_nombre field.
	 * @var        string
	 */
	protected $pro_nombre;

	/**
	 * The value for the pro_area_aplicacion field.
	 * @var        string
	 */
	protected $pro_area_aplicacion;

	/**
	 * The value for the pro_fecha_inicio field.
	 * @var        string
	 */
	protected $pro_fecha_inicio;

	/**
	 * The value for the pro_fecha_finalizacion field.
	 * @var        string
	 */
	protected $pro_fecha_finalizacion;

	/**
	 * The value for the pro_estado field.
	 * @var        string
	 */
	protected $pro_estado;

	/**
	 * The value for the pro_logo field.
	 * @var        string
	 */
	protected $pro_logo;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the pro_descripcion field.
	 * @var        string
	 */
	protected $pro_descripcion;

	/**
	 * @var        AgilhuUsuario
	 */
	protected $aAgilhuUsuario;

	/**
	 * @var        array AgilhuHistoriaUsuario[] Collection to store aggregation of AgilhuHistoriaUsuario objects.
	 */
	protected $collAgilhuHistoriaUsuarios;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAgilhuHistoriaUsuarios.
	 */
	private $lastAgilhuHistoriaUsuarioCriteria = null;

	/**
	 * @var        array AgilhuModulo[] Collection to store aggregation of AgilhuModulo objects.
	 */
	protected $collAgilhuModulos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAgilhuModulos.
	 */
	private $lastAgilhuModuloCriteria = null;

	/**
	 * @var        array AgilhuParticipante[] Collection to store aggregation of AgilhuParticipante objects.
	 */
	protected $collAgilhuParticipantes;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAgilhuParticipantes.
	 */
	private $lastAgilhuParticipanteCriteria = null;

	/**
	 * @var        array AgilhuPreguntas[] Collection to store aggregation of AgilhuPreguntas objects.
	 */
	protected $collAgilhuPreguntass;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAgilhuPreguntass.
	 */
	private $lastAgilhuPreguntasCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseAgilhuProyecto object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [pro_id] column value.
	 * 
	 * @return     int
	 */
	public function getProId()
	{
		return $this->pro_id;
	}

	/**
	 * Get the [usu_id] column value.
	 * 
	 * @return     int
	 */
	public function getUsuId()
	{
		return $this->usu_id;
	}

	/**
	 * Get the [pro_nombre_corto] column value.
	 * 
	 * @return     string
	 */
	public function getProNombreCorto()
	{
		return $this->pro_nombre_corto;
	}

	/**
	 * Get the [pro_nombre] column value.
	 * 
	 * @return     string
	 */
	public function getProNombre()
	{
		return $this->pro_nombre;
	}

	/**
	 * Get the [pro_area_aplicacion] column value.
	 * 
	 * @return     string
	 */
	public function getProAreaAplicacion()
	{
		return $this->pro_area_aplicacion;
	}

	/**
	 * Get the [optionally formatted] temporal [pro_fecha_inicio] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getProFechaInicio($format = 'Y-m-d')
	{
		if ($this->pro_fecha_inicio === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->pro_fecha_inicio);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->pro_fecha_inicio, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [pro_fecha_finalizacion] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getProFechaFinalizacion($format = 'Y-m-d')
	{
		if ($this->pro_fecha_finalizacion === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->pro_fecha_finalizacion);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->pro_fecha_finalizacion, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [pro_estado] column value.
	 * 
	 * @return     string
	 */
	public function getProEstado()
	{
		return $this->pro_estado;
	}

	/**
	 * Get the [pro_logo] column value.
	 * 
	 * @return     string
	 */
	public function getProLogo()
	{
		return $this->pro_logo;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->created_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->updated_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [pro_descripcion] column value.
	 * 
	 * @return     string
	 */
	public function getProDescripcion()
	{
		return $this->pro_descripcion;
	}

	/**
	 * Set the value of [pro_id] column.
	 * 
	 * @param      int $v new value
	 * @return     AgilhuProyecto The current object (for fluent API support)
	 */
	public function setProId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->pro_id !== $v) {
			$this->pro_id = $v;
			$this->modifiedColumns[] = AgilhuProyectoPeer::PRO_ID;
		}

		return $this;
	} // setProId()

	/**
	 * Set the value of [usu_id] column.
	 * 
	 * @param      int $v new value
	 * @return     AgilhuProyecto The current object (for fluent API support)
	 */
	public function setUsuId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->usu_id !== $v) {
			$this->usu_id = $v;
			$this->modifiedColumns[] = AgilhuProyectoPeer::USU_ID;
		}

		if ($this->aAgilhuUsuario !== null && $this->aAgilhuUsuario->getUsuId() !== $v) {
			$this->aAgilhuUsuario = null;
		}

		return $this;
	} // setUsuId()

	/**
	 * Set the value of [pro_nombre_corto] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuProyecto The current object (for fluent API support)
	 */
	public function setProNombreCorto($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pro_nombre_corto !== $v) {
			$this->pro_nombre_corto = $v;
			$this->modifiedColumns[] = AgilhuProyectoPeer::PRO_NOMBRE_CORTO;
		}

		return $this;
	} // setProNombreCorto()

	/**
	 * Set the value of [pro_nombre] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuProyecto The current object (for fluent API support)
	 */
	public function setProNombre($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pro_nombre !== $v) {
			$this->pro_nombre = $v;
			$this->modifiedColumns[] = AgilhuProyectoPeer::PRO_NOMBRE;
		}

		return $this;
	} // setProNombre()

	/**
	 * Set the value of [pro_area_aplicacion] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuProyecto The current object (for fluent API support)
	 */
	public function setProAreaAplicacion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pro_area_aplicacion !== $v) {
			$this->pro_area_aplicacion = $v;
			$this->modifiedColumns[] = AgilhuProyectoPeer::PRO_AREA_APLICACION;
		}

		return $this;
	} // setProAreaAplicacion()

	/**
	 * Sets the value of [pro_fecha_inicio] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     AgilhuProyecto The current object (for fluent API support)
	 */
	public function setProFechaInicio($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->pro_fecha_inicio !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->pro_fecha_inicio !== null && $tmpDt = new DateTime($this->pro_fecha_inicio)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->pro_fecha_inicio = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = AgilhuProyectoPeer::PRO_FECHA_INICIO;
			}
		} // if either are not null

		return $this;
	} // setProFechaInicio()

	/**
	 * Sets the value of [pro_fecha_finalizacion] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     AgilhuProyecto The current object (for fluent API support)
	 */
	public function setProFechaFinalizacion($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->pro_fecha_finalizacion !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->pro_fecha_finalizacion !== null && $tmpDt = new DateTime($this->pro_fecha_finalizacion)) ? $tmpDt->format('Y-m-d') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->pro_fecha_finalizacion = ($dt ? $dt->format('Y-m-d') : null);
				$this->modifiedColumns[] = AgilhuProyectoPeer::PRO_FECHA_FINALIZACION;
			}
		} // if either are not null

		return $this;
	} // setProFechaFinalizacion()

	/**
	 * Set the value of [pro_estado] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuProyecto The current object (for fluent API support)
	 */
	public function setProEstado($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pro_estado !== $v) {
			$this->pro_estado = $v;
			$this->modifiedColumns[] = AgilhuProyectoPeer::PRO_ESTADO;
		}

		return $this;
	} // setProEstado()

	/**
	 * Set the value of [pro_logo] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuProyecto The current object (for fluent API support)
	 */
	public function setProLogo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pro_logo !== $v) {
			$this->pro_logo = $v;
			$this->modifiedColumns[] = AgilhuProyectoPeer::PRO_LOGO;
		}

		return $this;
	} // setProLogo()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     AgilhuProyecto The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = AgilhuProyectoPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     AgilhuProyecto The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = AgilhuProyectoPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Set the value of [pro_descripcion] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuProyecto The current object (for fluent API support)
	 */
	public function setProDescripcion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pro_descripcion !== $v) {
			$this->pro_descripcion = $v;
			$this->modifiedColumns[] = AgilhuProyectoPeer::PRO_DESCRIPCION;
		}

		return $this;
	} // setProDescripcion()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->pro_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->usu_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->pro_nombre_corto = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->pro_nombre = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->pro_area_aplicacion = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->pro_fecha_inicio = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->pro_fecha_finalizacion = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->pro_estado = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->pro_logo = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->created_at = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->updated_at = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->pro_descripcion = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 12; // 12 = AgilhuProyectoPeer::NUM_COLUMNS - AgilhuProyectoPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating AgilhuProyecto object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aAgilhuUsuario !== null && $this->usu_id !== $this->aAgilhuUsuario->getUsuId()) {
			$this->aAgilhuUsuario = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AgilhuProyectoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = AgilhuProyectoPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aAgilhuUsuario = null;
			$this->collAgilhuHistoriaUsuarios = null;
			$this->lastAgilhuHistoriaUsuarioCriteria = null;

			$this->collAgilhuModulos = null;
			$this->lastAgilhuModuloCriteria = null;

			$this->collAgilhuParticipantes = null;
			$this->lastAgilhuParticipanteCriteria = null;

			$this->collAgilhuPreguntass = null;
			$this->lastAgilhuPreguntasCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseAgilhuProyecto:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AgilhuProyectoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			AgilhuProyectoPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseAgilhuProyecto:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseAgilhuProyecto:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(AgilhuProyectoPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

    if ($this->isModified() && !$this->isColumnModified(AgilhuProyectoPeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AgilhuProyectoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseAgilhuProyecto:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			AgilhuProyectoPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aAgilhuUsuario !== null) {
				if ($this->aAgilhuUsuario->isModified() || $this->aAgilhuUsuario->isNew()) {
					$affectedRows += $this->aAgilhuUsuario->save($con);
				}
				$this->setAgilhuUsuario($this->aAgilhuUsuario);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = AgilhuProyectoPeer::PRO_ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = AgilhuProyectoPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setProId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += AgilhuProyectoPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collAgilhuHistoriaUsuarios !== null) {
				foreach ($this->collAgilhuHistoriaUsuarios as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collAgilhuModulos !== null) {
				foreach ($this->collAgilhuModulos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collAgilhuParticipantes !== null) {
				foreach ($this->collAgilhuParticipantes as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collAgilhuPreguntass !== null) {
				foreach ($this->collAgilhuPreguntass as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aAgilhuUsuario !== null) {
				if (!$this->aAgilhuUsuario->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aAgilhuUsuario->getValidationFailures());
				}
			}


			if (($retval = AgilhuProyectoPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collAgilhuHistoriaUsuarios !== null) {
					foreach ($this->collAgilhuHistoriaUsuarios as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collAgilhuModulos !== null) {
					foreach ($this->collAgilhuModulos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collAgilhuParticipantes !== null) {
					foreach ($this->collAgilhuParticipantes as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collAgilhuPreguntass !== null) {
					foreach ($this->collAgilhuPreguntass as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AgilhuProyectoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getProId();
				break;
			case 1:
				return $this->getUsuId();
				break;
			case 2:
				return $this->getProNombreCorto();
				break;
			case 3:
				return $this->getProNombre();
				break;
			case 4:
				return $this->getProAreaAplicacion();
				break;
			case 5:
				return $this->getProFechaInicio();
				break;
			case 6:
				return $this->getProFechaFinalizacion();
				break;
			case 7:
				return $this->getProEstado();
				break;
			case 8:
				return $this->getProLogo();
				break;
			case 9:
				return $this->getCreatedAt();
				break;
			case 10:
				return $this->getUpdatedAt();
				break;
			case 11:
				return $this->getProDescripcion();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = AgilhuProyectoPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getProId(),
			$keys[1] => $this->getUsuId(),
			$keys[2] => $this->getProNombreCorto(),
			$keys[3] => $this->getProNombre(),
			$keys[4] => $this->getProAreaAplicacion(),
			$keys[5] => $this->getProFechaInicio(),
			$keys[6] => $this->getProFechaFinalizacion(),
			$keys[7] => $this->getProEstado(),
			$keys[8] => $this->getProLogo(),
			$keys[9] => $this->getCreatedAt(),
			$keys[10] => $this->getUpdatedAt(),
			$keys[11] => $this->getProDescripcion(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AgilhuProyectoPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setProId($value);
				break;
			case 1:
				$this->setUsuId($value);
				break;
			case 2:
				$this->setProNombreCorto($value);
				break;
			case 3:
				$this->setProNombre($value);
				break;
			case 4:
				$this->setProAreaAplicacion($value);
				break;
			case 5:
				$this->setProFechaInicio($value);
				break;
			case 6:
				$this->setProFechaFinalizacion($value);
				break;
			case 7:
				$this->setProEstado($value);
				break;
			case 8:
				$this->setProLogo($value);
				break;
			case 9:
				$this->setCreatedAt($value);
				break;
			case 10:
				$this->setUpdatedAt($value);
				break;
			case 11:
				$this->setProDescripcion($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = AgilhuProyectoPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setProId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setUsuId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setProNombreCorto($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setProNombre($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setProAreaAplicacion($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setProFechaInicio($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setProFechaFinalizacion($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setProEstado($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setProLogo($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setCreatedAt($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setUpdatedAt($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setProDescripcion($arr[$keys[11]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(AgilhuProyectoPeer::DATABASE_NAME);

		if ($this->isColumnModified(AgilhuProyectoPeer::PRO_ID)) $criteria->add(AgilhuProyectoPeer::PRO_ID, $this->pro_id);
		if ($this->isColumnModified(AgilhuProyectoPeer::USU_ID)) $criteria->add(AgilhuProyectoPeer::USU_ID, $this->usu_id);
		if ($this->isColumnModified(AgilhuProyectoPeer::PRO_NOMBRE_CORTO)) $criteria->add(AgilhuProyectoPeer::PRO_NOMBRE_CORTO, $this->pro_nombre_corto);
		if ($this->isColumnModified(AgilhuProyectoPeer::PRO_NOMBRE)) $criteria->add(AgilhuProyectoPeer::PRO_NOMBRE, $this->pro_nombre);
		if ($this->isColumnModified(AgilhuProyectoPeer::PRO_AREA_APLICACION)) $criteria->add(AgilhuProyectoPeer::PRO_AREA_APLICACION, $this->pro_area_aplicacion);
		if ($this->isColumnModified(AgilhuProyectoPeer::PRO_FECHA_INICIO)) $criteria->add(AgilhuProyectoPeer::PRO_FECHA_INICIO, $this->pro_fecha_inicio);
		if ($this->isColumnModified(AgilhuProyectoPeer::PRO_FECHA_FINALIZACION)) $criteria->add(AgilhuProyectoPeer::PRO_FECHA_FINALIZACION, $this->pro_fecha_finalizacion);
		if ($this->isColumnModified(AgilhuProyectoPeer::PRO_ESTADO)) $criteria->add(AgilhuProyectoPeer::PRO_ESTADO, $this->pro_estado);
		if ($this->isColumnModified(AgilhuProyectoPeer::PRO_LOGO)) $criteria->add(AgilhuProyectoPeer::PRO_LOGO, $this->pro_logo);
		if ($this->isColumnModified(AgilhuProyectoPeer::CREATED_AT)) $criteria->add(AgilhuProyectoPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(AgilhuProyectoPeer::UPDATED_AT)) $criteria->add(AgilhuProyectoPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(AgilhuProyectoPeer::PRO_DESCRIPCION)) $criteria->add(AgilhuProyectoPeer::PRO_DESCRIPCION, $this->pro_descripcion);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(AgilhuProyectoPeer::DATABASE_NAME);

		$criteria->add(AgilhuProyectoPeer::PRO_ID, $this->pro_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getProId();
	}

	/**
	 * Generic method to set the primary key (pro_id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setProId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of AgilhuProyecto (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setUsuId($this->usu_id);

		$copyObj->setProNombreCorto($this->pro_nombre_corto);

		$copyObj->setProNombre($this->pro_nombre);

		$copyObj->setProAreaAplicacion($this->pro_area_aplicacion);

		$copyObj->setProFechaInicio($this->pro_fecha_inicio);

		$copyObj->setProFechaFinalizacion($this->pro_fecha_finalizacion);

		$copyObj->setProEstado($this->pro_estado);

		$copyObj->setProLogo($this->pro_logo);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setProDescripcion($this->pro_descripcion);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getAgilhuHistoriaUsuarios() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAgilhuHistoriaUsuario($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getAgilhuModulos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAgilhuModulo($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getAgilhuParticipantes() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAgilhuParticipante($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getAgilhuPreguntass() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAgilhuPreguntas($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setProId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     AgilhuProyecto Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     AgilhuProyectoPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new AgilhuProyectoPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a AgilhuUsuario object.
	 *
	 * @param      AgilhuUsuario $v
	 * @return     AgilhuProyecto The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setAgilhuUsuario(AgilhuUsuario $v = null)
	{
		if ($v === null) {
			$this->setUsuId(NULL);
		} else {
			$this->setUsuId($v->getUsuId());
		}

		$this->aAgilhuUsuario = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the AgilhuUsuario object, it will not be re-added.
		if ($v !== null) {
			$v->addAgilhuProyecto($this);
		}

		return $this;
	}


	/**
	 * Get the associated AgilhuUsuario object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     AgilhuUsuario The associated AgilhuUsuario object.
	 * @throws     PropelException
	 */
	public function getAgilhuUsuario(PropelPDO $con = null)
	{
		if ($this->aAgilhuUsuario === null && ($this->usu_id !== null)) {
			$c = new Criteria(AgilhuUsuarioPeer::DATABASE_NAME);
			$c->add(AgilhuUsuarioPeer::USU_ID, $this->usu_id);
			$this->aAgilhuUsuario = AgilhuUsuarioPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aAgilhuUsuario->addAgilhuProyectos($this);
			 */
		}
		return $this->aAgilhuUsuario;
	}

	/**
	 * Clears out the collAgilhuHistoriaUsuarios collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAgilhuHistoriaUsuarios()
	 */
	public function clearAgilhuHistoriaUsuarios()
	{
		$this->collAgilhuHistoriaUsuarios = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAgilhuHistoriaUsuarios collection (array).
	 *
	 * By default this just sets the collAgilhuHistoriaUsuarios collection to an empty array (like clearcollAgilhuHistoriaUsuarios());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAgilhuHistoriaUsuarios()
	{
		$this->collAgilhuHistoriaUsuarios = array();
	}

	/**
	 * Gets an array of AgilhuHistoriaUsuario objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this AgilhuProyecto has previously been saved, it will retrieve
	 * related AgilhuHistoriaUsuarios from storage. If this AgilhuProyecto is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array AgilhuHistoriaUsuario[]
	 * @throws     PropelException
	 */
	public function getAgilhuHistoriaUsuarios($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AgilhuProyectoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAgilhuHistoriaUsuarios === null) {
			if ($this->isNew()) {
			   $this->collAgilhuHistoriaUsuarios = array();
			} else {

				$criteria->add(AgilhuHistoriaUsuarioPeer::PRO_ID, $this->pro_id);

				AgilhuHistoriaUsuarioPeer::addSelectColumns($criteria);
				$this->collAgilhuHistoriaUsuarios = AgilhuHistoriaUsuarioPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AgilhuHistoriaUsuarioPeer::PRO_ID, $this->pro_id);

				AgilhuHistoriaUsuarioPeer::addSelectColumns($criteria);
				if (!isset($this->lastAgilhuHistoriaUsuarioCriteria) || !$this->lastAgilhuHistoriaUsuarioCriteria->equals($criteria)) {
					$this->collAgilhuHistoriaUsuarios = AgilhuHistoriaUsuarioPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAgilhuHistoriaUsuarioCriteria = $criteria;
		return $this->collAgilhuHistoriaUsuarios;
	}

	/**
	 * Returns the number of related AgilhuHistoriaUsuario objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related AgilhuHistoriaUsuario objects.
	 * @throws     PropelException
	 */
	public function countAgilhuHistoriaUsuarios(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AgilhuProyectoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAgilhuHistoriaUsuarios === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AgilhuHistoriaUsuarioPeer::PRO_ID, $this->pro_id);

				$count = AgilhuHistoriaUsuarioPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AgilhuHistoriaUsuarioPeer::PRO_ID, $this->pro_id);

				if (!isset($this->lastAgilhuHistoriaUsuarioCriteria) || !$this->lastAgilhuHistoriaUsuarioCriteria->equals($criteria)) {
					$count = AgilhuHistoriaUsuarioPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collAgilhuHistoriaUsuarios);
				}
			} else {
				$count = count($this->collAgilhuHistoriaUsuarios);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a AgilhuHistoriaUsuario object to this object
	 * through the AgilhuHistoriaUsuario foreign key attribute.
	 *
	 * @param      AgilhuHistoriaUsuario $l AgilhuHistoriaUsuario
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAgilhuHistoriaUsuario(AgilhuHistoriaUsuario $l)
	{
		if ($this->collAgilhuHistoriaUsuarios === null) {
			$this->initAgilhuHistoriaUsuarios();
		}
		if (!in_array($l, $this->collAgilhuHistoriaUsuarios, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAgilhuHistoriaUsuarios, $l);
			$l->setAgilhuProyecto($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this AgilhuProyecto is new, it will return
	 * an empty collection; or if this AgilhuProyecto has previously
	 * been saved, it will retrieve related AgilhuHistoriaUsuarios from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in AgilhuProyecto.
	 */
	public function getAgilhuHistoriaUsuariosJoinAgilhuModulo($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AgilhuProyectoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAgilhuHistoriaUsuarios === null) {
			if ($this->isNew()) {
				$this->collAgilhuHistoriaUsuarios = array();
			} else {

				$criteria->add(AgilhuHistoriaUsuarioPeer::PRO_ID, $this->pro_id);

				$this->collAgilhuHistoriaUsuarios = AgilhuHistoriaUsuarioPeer::doSelectJoinAgilhuModulo($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(AgilhuHistoriaUsuarioPeer::PRO_ID, $this->pro_id);

			if (!isset($this->lastAgilhuHistoriaUsuarioCriteria) || !$this->lastAgilhuHistoriaUsuarioCriteria->equals($criteria)) {
				$this->collAgilhuHistoriaUsuarios = AgilhuHistoriaUsuarioPeer::doSelectJoinAgilhuModulo($criteria, $con, $join_behavior);
			}
		}
		$this->lastAgilhuHistoriaUsuarioCriteria = $criteria;

		return $this->collAgilhuHistoriaUsuarios;
	}

	/**
	 * Clears out the collAgilhuModulos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAgilhuModulos()
	 */
	public function clearAgilhuModulos()
	{
		$this->collAgilhuModulos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAgilhuModulos collection (array).
	 *
	 * By default this just sets the collAgilhuModulos collection to an empty array (like clearcollAgilhuModulos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAgilhuModulos()
	{
		$this->collAgilhuModulos = array();
	}

	/**
	 * Gets an array of AgilhuModulo objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this AgilhuProyecto has previously been saved, it will retrieve
	 * related AgilhuModulos from storage. If this AgilhuProyecto is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array AgilhuModulo[]
	 * @throws     PropelException
	 */
	public function getAgilhuModulos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AgilhuProyectoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAgilhuModulos === null) {
			if ($this->isNew()) {
			   $this->collAgilhuModulos = array();
			} else {

				$criteria->add(AgilhuModuloPeer::PRO_ID, $this->pro_id);

				AgilhuModuloPeer::addSelectColumns($criteria);
				$this->collAgilhuModulos = AgilhuModuloPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AgilhuModuloPeer::PRO_ID, $this->pro_id);

				AgilhuModuloPeer::addSelectColumns($criteria);
				if (!isset($this->lastAgilhuModuloCriteria) || !$this->lastAgilhuModuloCriteria->equals($criteria)) {
					$this->collAgilhuModulos = AgilhuModuloPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAgilhuModuloCriteria = $criteria;
		return $this->collAgilhuModulos;
	}

	/**
	 * Returns the number of related AgilhuModulo objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related AgilhuModulo objects.
	 * @throws     PropelException
	 */
	public function countAgilhuModulos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AgilhuProyectoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAgilhuModulos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AgilhuModuloPeer::PRO_ID, $this->pro_id);

				$count = AgilhuModuloPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AgilhuModuloPeer::PRO_ID, $this->pro_id);

				if (!isset($this->lastAgilhuModuloCriteria) || !$this->lastAgilhuModuloCriteria->equals($criteria)) {
					$count = AgilhuModuloPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collAgilhuModulos);
				}
			} else {
				$count = count($this->collAgilhuModulos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a AgilhuModulo object to this object
	 * through the AgilhuModulo foreign key attribute.
	 *
	 * @param      AgilhuModulo $l AgilhuModulo
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAgilhuModulo(AgilhuModulo $l)
	{
		if ($this->collAgilhuModulos === null) {
			$this->initAgilhuModulos();
		}
		if (!in_array($l, $this->collAgilhuModulos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAgilhuModulos, $l);
			$l->setAgilhuProyecto($this);
		}
	}

	/**
	 * Clears out the collAgilhuParticipantes collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAgilhuParticipantes()
	 */
	public function clearAgilhuParticipantes()
	{
		$this->collAgilhuParticipantes = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAgilhuParticipantes collection (array).
	 *
	 * By default this just sets the collAgilhuParticipantes collection to an empty array (like clearcollAgilhuParticipantes());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAgilhuParticipantes()
	{
		$this->collAgilhuParticipantes = array();
	}

	/**
	 * Gets an array of AgilhuParticipante objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this AgilhuProyecto has previously been saved, it will retrieve
	 * related AgilhuParticipantes from storage. If this AgilhuProyecto is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array AgilhuParticipante[]
	 * @throws     PropelException
	 */
	public function getAgilhuParticipantes($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AgilhuProyectoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAgilhuParticipantes === null) {
			if ($this->isNew()) {
			   $this->collAgilhuParticipantes = array();
			} else {

				$criteria->add(AgilhuParticipantePeer::PRO_ID, $this->pro_id);

				AgilhuParticipantePeer::addSelectColumns($criteria);
				$this->collAgilhuParticipantes = AgilhuParticipantePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AgilhuParticipantePeer::PRO_ID, $this->pro_id);

				AgilhuParticipantePeer::addSelectColumns($criteria);
				if (!isset($this->lastAgilhuParticipanteCriteria) || !$this->lastAgilhuParticipanteCriteria->equals($criteria)) {
					$this->collAgilhuParticipantes = AgilhuParticipantePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAgilhuParticipanteCriteria = $criteria;
		return $this->collAgilhuParticipantes;
	}

	/**
	 * Returns the number of related AgilhuParticipante objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related AgilhuParticipante objects.
	 * @throws     PropelException
	 */
	public function countAgilhuParticipantes(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AgilhuProyectoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAgilhuParticipantes === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AgilhuParticipantePeer::PRO_ID, $this->pro_id);

				$count = AgilhuParticipantePeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AgilhuParticipantePeer::PRO_ID, $this->pro_id);

				if (!isset($this->lastAgilhuParticipanteCriteria) || !$this->lastAgilhuParticipanteCriteria->equals($criteria)) {
					$count = AgilhuParticipantePeer::doCount($criteria, $con);
				} else {
					$count = count($this->collAgilhuParticipantes);
				}
			} else {
				$count = count($this->collAgilhuParticipantes);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a AgilhuParticipante object to this object
	 * through the AgilhuParticipante foreign key attribute.
	 *
	 * @param      AgilhuParticipante $l AgilhuParticipante
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAgilhuParticipante(AgilhuParticipante $l)
	{
		if ($this->collAgilhuParticipantes === null) {
			$this->initAgilhuParticipantes();
		}
		if (!in_array($l, $this->collAgilhuParticipantes, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAgilhuParticipantes, $l);
			$l->setAgilhuProyecto($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this AgilhuProyecto is new, it will return
	 * an empty collection; or if this AgilhuProyecto has previously
	 * been saved, it will retrieve related AgilhuParticipantes from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in AgilhuProyecto.
	 */
	public function getAgilhuParticipantesJoinAgilhuUsuario($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AgilhuProyectoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAgilhuParticipantes === null) {
			if ($this->isNew()) {
				$this->collAgilhuParticipantes = array();
			} else {

				$criteria->add(AgilhuParticipantePeer::PRO_ID, $this->pro_id);

				$this->collAgilhuParticipantes = AgilhuParticipantePeer::doSelectJoinAgilhuUsuario($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(AgilhuParticipantePeer::PRO_ID, $this->pro_id);

			if (!isset($this->lastAgilhuParticipanteCriteria) || !$this->lastAgilhuParticipanteCriteria->equals($criteria)) {
				$this->collAgilhuParticipantes = AgilhuParticipantePeer::doSelectJoinAgilhuUsuario($criteria, $con, $join_behavior);
			}
		}
		$this->lastAgilhuParticipanteCriteria = $criteria;

		return $this->collAgilhuParticipantes;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this AgilhuProyecto is new, it will return
	 * an empty collection; or if this AgilhuProyecto has previously
	 * been saved, it will retrieve related AgilhuParticipantes from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in AgilhuProyecto.
	 */
	public function getAgilhuParticipantesJoinAgilhuRolProyecto($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AgilhuProyectoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAgilhuParticipantes === null) {
			if ($this->isNew()) {
				$this->collAgilhuParticipantes = array();
			} else {

				$criteria->add(AgilhuParticipantePeer::PRO_ID, $this->pro_id);

				$this->collAgilhuParticipantes = AgilhuParticipantePeer::doSelectJoinAgilhuRolProyecto($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(AgilhuParticipantePeer::PRO_ID, $this->pro_id);

			if (!isset($this->lastAgilhuParticipanteCriteria) || !$this->lastAgilhuParticipanteCriteria->equals($criteria)) {
				$this->collAgilhuParticipantes = AgilhuParticipantePeer::doSelectJoinAgilhuRolProyecto($criteria, $con, $join_behavior);
			}
		}
		$this->lastAgilhuParticipanteCriteria = $criteria;

		return $this->collAgilhuParticipantes;
	}

	/**
	 * Clears out the collAgilhuPreguntass collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAgilhuPreguntass()
	 */
	public function clearAgilhuPreguntass()
	{
		$this->collAgilhuPreguntass = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAgilhuPreguntass collection (array).
	 *
	 * By default this just sets the collAgilhuPreguntass collection to an empty array (like clearcollAgilhuPreguntass());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAgilhuPreguntass()
	{
		$this->collAgilhuPreguntass = array();
	}

	/**
	 * Gets an array of AgilhuPreguntas objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this AgilhuProyecto has previously been saved, it will retrieve
	 * related AgilhuPreguntass from storage. If this AgilhuProyecto is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array AgilhuPreguntas[]
	 * @throws     PropelException
	 */
	public function getAgilhuPreguntass($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AgilhuProyectoPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAgilhuPreguntass === null) {
			if ($this->isNew()) {
			   $this->collAgilhuPreguntass = array();
			} else {

				$criteria->add(AgilhuPreguntasPeer::PRE_PRO_ID, $this->pro_id);

				AgilhuPreguntasPeer::addSelectColumns($criteria);
				$this->collAgilhuPreguntass = AgilhuPreguntasPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AgilhuPreguntasPeer::PRE_PRO_ID, $this->pro_id);

				AgilhuPreguntasPeer::addSelectColumns($criteria);
				if (!isset($this->lastAgilhuPreguntasCriteria) || !$this->lastAgilhuPreguntasCriteria->equals($criteria)) {
					$this->collAgilhuPreguntass = AgilhuPreguntasPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAgilhuPreguntasCriteria = $criteria;
		return $this->collAgilhuPreguntass;
	}

	/**
	 * Returns the number of related AgilhuPreguntas objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related AgilhuPreguntas objects.
	 * @throws     PropelException
	 */
	public function countAgilhuPreguntass(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AgilhuProyectoPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAgilhuPreguntass === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AgilhuPreguntasPeer::PRE_PRO_ID, $this->pro_id);

				$count = AgilhuPreguntasPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AgilhuPreguntasPeer::PRE_PRO_ID, $this->pro_id);

				if (!isset($this->lastAgilhuPreguntasCriteria) || !$this->lastAgilhuPreguntasCriteria->equals($criteria)) {
					$count = AgilhuPreguntasPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collAgilhuPreguntass);
				}
			} else {
				$count = count($this->collAgilhuPreguntass);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a AgilhuPreguntas object to this object
	 * through the AgilhuPreguntas foreign key attribute.
	 *
	 * @param      AgilhuPreguntas $l AgilhuPreguntas
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAgilhuPreguntas(AgilhuPreguntas $l)
	{
		if ($this->collAgilhuPreguntass === null) {
			$this->initAgilhuPreguntass();
		}
		if (!in_array($l, $this->collAgilhuPreguntass, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAgilhuPreguntass, $l);
			$l->setAgilhuProyecto($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collAgilhuHistoriaUsuarios) {
				foreach ((array) $this->collAgilhuHistoriaUsuarios as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collAgilhuModulos) {
				foreach ((array) $this->collAgilhuModulos as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collAgilhuParticipantes) {
				foreach ((array) $this->collAgilhuParticipantes as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collAgilhuPreguntass) {
				foreach ((array) $this->collAgilhuPreguntass as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collAgilhuHistoriaUsuarios = null;
		$this->collAgilhuModulos = null;
		$this->collAgilhuParticipantes = null;
		$this->collAgilhuPreguntass = null;
			$this->aAgilhuUsuario = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseAgilhuProyecto:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseAgilhuProyecto::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseAgilhuProyecto
