<?php

/**
 * Base static class for performing query and update operations on the 'agilhu_prueba_experto' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Jun 28 16:09:55 2010
 *
 * @package    lib.model.om
 */
abstract class BaseAgilhuPruebaExpertoPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'agilhu_prueba_experto';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.AgilhuPruebaExperto';

	/** The total number of columns. */
	const NUM_COLUMNS = 11;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the PRU_FECHA_EVALUCION field */
	const PRU_FECHA_EVALUCION = 'agilhu_prueba_experto.PRU_FECHA_EVALUCION';

	/** the column name for the HIS_ID_ASOCIADA field */
	const HIS_ID_ASOCIADA = 'agilhu_prueba_experto.HIS_ID_ASOCIADA';

	/** the column name for the USU_EVALUADOR_ID field */
	const USU_EVALUADOR_ID = 'agilhu_prueba_experto.USU_EVALUADOR_ID';

	/** the column name for the PRU_PROMEDIO field */
	const PRU_PROMEDIO = 'agilhu_prueba_experto.PRU_PROMEDIO';

	/** the column name for the PRU_COMENTARIOS field */
	const PRU_COMENTARIOS = 'agilhu_prueba_experto.PRU_COMENTARIOS';

	/** the column name for the PRU_INDEPENDIENTE field */
	const PRU_INDEPENDIENTE = 'agilhu_prueba_experto.PRU_INDEPENDIENTE';

	/** the column name for the PRU_NEGOCIABLE field */
	const PRU_NEGOCIABLE = 'agilhu_prueba_experto.PRU_NEGOCIABLE';

	/** the column name for the PRU_VALIOSA field */
	const PRU_VALIOSA = 'agilhu_prueba_experto.PRU_VALIOSA';

	/** the column name for the PRU_ESTIMABLE field */
	const PRU_ESTIMABLE = 'agilhu_prueba_experto.PRU_ESTIMABLE';

	/** the column name for the PRU_PEQUENA field */
	const PRU_PEQUENA = 'agilhu_prueba_experto.PRU_PEQUENA';

	/** the column name for the PRU_TESTEABLE field */
	const PRU_TESTEABLE = 'agilhu_prueba_experto.PRU_TESTEABLE';

	/**
	 * An identiy map to hold any loaded instances of AgilhuPruebaExperto objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array AgilhuPruebaExperto[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('PruFechaEvalucion', 'HisIdAsociada', 'UsuEvaluadorId', 'PruPromedio', 'PruComentarios', 'PruIndependiente', 'PruNegociable', 'PruValiosa', 'PruEstimable', 'PruPequena', 'PruTesteable', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('pruFechaEvalucion', 'hisIdAsociada', 'usuEvaluadorId', 'pruPromedio', 'pruComentarios', 'pruIndependiente', 'pruNegociable', 'pruValiosa', 'pruEstimable', 'pruPequena', 'pruTesteable', ),
		BasePeer::TYPE_COLNAME => array (self::PRU_FECHA_EVALUCION, self::HIS_ID_ASOCIADA, self::USU_EVALUADOR_ID, self::PRU_PROMEDIO, self::PRU_COMENTARIOS, self::PRU_INDEPENDIENTE, self::PRU_NEGOCIABLE, self::PRU_VALIOSA, self::PRU_ESTIMABLE, self::PRU_PEQUENA, self::PRU_TESTEABLE, ),
		BasePeer::TYPE_FIELDNAME => array ('pru_fecha_evalucion', 'his_id_asociada', 'usu_evaluador_id', 'pru_promedio', 'pru_comentarios', 'pru_independiente', 'pru_negociable', 'pru_valiosa', 'pru_estimable', 'pru_pequena', 'pru_testeable', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('PruFechaEvalucion' => 0, 'HisIdAsociada' => 1, 'UsuEvaluadorId' => 2, 'PruPromedio' => 3, 'PruComentarios' => 4, 'PruIndependiente' => 5, 'PruNegociable' => 6, 'PruValiosa' => 7, 'PruEstimable' => 8, 'PruPequena' => 9, 'PruTesteable' => 10, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('pruFechaEvalucion' => 0, 'hisIdAsociada' => 1, 'usuEvaluadorId' => 2, 'pruPromedio' => 3, 'pruComentarios' => 4, 'pruIndependiente' => 5, 'pruNegociable' => 6, 'pruValiosa' => 7, 'pruEstimable' => 8, 'pruPequena' => 9, 'pruTesteable' => 10, ),
		BasePeer::TYPE_COLNAME => array (self::PRU_FECHA_EVALUCION => 0, self::HIS_ID_ASOCIADA => 1, self::USU_EVALUADOR_ID => 2, self::PRU_PROMEDIO => 3, self::PRU_COMENTARIOS => 4, self::PRU_INDEPENDIENTE => 5, self::PRU_NEGOCIABLE => 6, self::PRU_VALIOSA => 7, self::PRU_ESTIMABLE => 8, self::PRU_PEQUENA => 9, self::PRU_TESTEABLE => 10, ),
		BasePeer::TYPE_FIELDNAME => array ('pru_fecha_evalucion' => 0, 'his_id_asociada' => 1, 'usu_evaluador_id' => 2, 'pru_promedio' => 3, 'pru_comentarios' => 4, 'pru_independiente' => 5, 'pru_negociable' => 6, 'pru_valiosa' => 7, 'pru_estimable' => 8, 'pru_pequena' => 9, 'pru_testeable' => 10, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new AgilhuPruebaExpertoMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. AgilhuPruebaExpertoPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(AgilhuPruebaExpertoPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(AgilhuPruebaExpertoPeer::PRU_FECHA_EVALUCION);

		$criteria->addSelectColumn(AgilhuPruebaExpertoPeer::HIS_ID_ASOCIADA);

		$criteria->addSelectColumn(AgilhuPruebaExpertoPeer::USU_EVALUADOR_ID);

		$criteria->addSelectColumn(AgilhuPruebaExpertoPeer::PRU_PROMEDIO);

		$criteria->addSelectColumn(AgilhuPruebaExpertoPeer::PRU_COMENTARIOS);

		$criteria->addSelectColumn(AgilhuPruebaExpertoPeer::PRU_INDEPENDIENTE);

		$criteria->addSelectColumn(AgilhuPruebaExpertoPeer::PRU_NEGOCIABLE);

		$criteria->addSelectColumn(AgilhuPruebaExpertoPeer::PRU_VALIOSA);

		$criteria->addSelectColumn(AgilhuPruebaExpertoPeer::PRU_ESTIMABLE);

		$criteria->addSelectColumn(AgilhuPruebaExpertoPeer::PRU_PEQUENA);

		$criteria->addSelectColumn(AgilhuPruebaExpertoPeer::PRU_TESTEABLE);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(AgilhuPruebaExpertoPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AgilhuPruebaExpertoPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(AgilhuPruebaExpertoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseAgilhuPruebaExpertoPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseAgilhuPruebaExpertoPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     AgilhuPruebaExperto
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = AgilhuPruebaExpertoPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return AgilhuPruebaExpertoPeer::populateObjects(AgilhuPruebaExpertoPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseAgilhuPruebaExpertoPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseAgilhuPruebaExpertoPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(AgilhuPruebaExpertoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			AgilhuPruebaExpertoPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      AgilhuPruebaExperto $value A AgilhuPruebaExperto object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(AgilhuPruebaExperto $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = serialize(array((string) $obj->getPruFechaEvalucion(), (string) $obj->getHisIdAsociada(), (string) $obj->getUsuEvaluadorId()));
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A AgilhuPruebaExperto object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof AgilhuPruebaExperto) {
				$key = serialize(array((string) $value->getPruFechaEvalucion(), (string) $value->getHisIdAsociada(), (string) $value->getUsuEvaluadorId()));
			} elseif (is_array($value) && count($value) === 3) {
				// assume we've been passed a primary key
				$key = serialize(array((string) $value[0], (string) $value[1], (string) $value[2]));
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or AgilhuPruebaExperto object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     AgilhuPruebaExperto Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null && $row[$startcol + 1] === null && $row[$startcol + 2] === null) {
			return null;
		}
		return serialize(array((string) $row[$startcol + 0], (string) $row[$startcol + 1], (string) $row[$startcol + 2]));
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = AgilhuPruebaExpertoPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = AgilhuPruebaExpertoPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = AgilhuPruebaExpertoPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				AgilhuPruebaExpertoPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the number of rows matching criteria, joining the related AgilhuHistoriaUsuario table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAgilhuHistoriaUsuario(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(AgilhuPruebaExpertoPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AgilhuPruebaExpertoPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(AgilhuPruebaExpertoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(AgilhuPruebaExpertoPeer::HIS_ID_ASOCIADA,), array(AgilhuHistoriaUsuarioPeer::HIS_ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseAgilhuPruebaExpertoPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseAgilhuPruebaExpertoPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related AgilhuUsuario table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAgilhuUsuario(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(AgilhuPruebaExpertoPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AgilhuPruebaExpertoPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(AgilhuPruebaExpertoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(AgilhuPruebaExpertoPeer::USU_EVALUADOR_ID,), array(AgilhuUsuarioPeer::USU_ID,), $join_behavior);


    foreach (sfMixer::getCallables('BaseAgilhuPruebaExpertoPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseAgilhuPruebaExpertoPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of AgilhuPruebaExperto objects pre-filled with their AgilhuHistoriaUsuario objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of AgilhuPruebaExperto objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAgilhuHistoriaUsuario(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseAgilhuPruebaExpertoPeer:doSelectJoin:doSelectJoin') as $callable)
    {
      call_user_func($callable, 'BaseAgilhuPruebaExpertoPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		AgilhuPruebaExpertoPeer::addSelectColumns($c);
		$startcol = (AgilhuPruebaExpertoPeer::NUM_COLUMNS - AgilhuPruebaExpertoPeer::NUM_LAZY_LOAD_COLUMNS);
		AgilhuHistoriaUsuarioPeer::addSelectColumns($c);

		$c->addJoin(array(AgilhuPruebaExpertoPeer::HIS_ID_ASOCIADA,), array(AgilhuHistoriaUsuarioPeer::HIS_ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = AgilhuPruebaExpertoPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = AgilhuPruebaExpertoPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = AgilhuPruebaExpertoPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				AgilhuPruebaExpertoPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = AgilhuHistoriaUsuarioPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = AgilhuHistoriaUsuarioPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = AgilhuHistoriaUsuarioPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					AgilhuHistoriaUsuarioPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (AgilhuPruebaExperto) to $obj2 (AgilhuHistoriaUsuario)
				$obj2->addAgilhuPruebaExperto($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of AgilhuPruebaExperto objects pre-filled with their AgilhuUsuario objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of AgilhuPruebaExperto objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAgilhuUsuario(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		AgilhuPruebaExpertoPeer::addSelectColumns($c);
		$startcol = (AgilhuPruebaExpertoPeer::NUM_COLUMNS - AgilhuPruebaExpertoPeer::NUM_LAZY_LOAD_COLUMNS);
		AgilhuUsuarioPeer::addSelectColumns($c);

		$c->addJoin(array(AgilhuPruebaExpertoPeer::USU_EVALUADOR_ID,), array(AgilhuUsuarioPeer::USU_ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = AgilhuPruebaExpertoPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = AgilhuPruebaExpertoPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = AgilhuPruebaExpertoPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				AgilhuPruebaExpertoPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = AgilhuUsuarioPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = AgilhuUsuarioPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = AgilhuUsuarioPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					AgilhuUsuarioPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (AgilhuPruebaExperto) to $obj2 (AgilhuUsuario)
				$obj2->addAgilhuPruebaExperto($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(AgilhuPruebaExpertoPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AgilhuPruebaExpertoPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(AgilhuPruebaExpertoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(AgilhuPruebaExpertoPeer::HIS_ID_ASOCIADA,), array(AgilhuHistoriaUsuarioPeer::HIS_ID,), $join_behavior);
		$criteria->addJoin(array(AgilhuPruebaExpertoPeer::USU_EVALUADOR_ID,), array(AgilhuUsuarioPeer::USU_ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseAgilhuPruebaExpertoPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseAgilhuPruebaExpertoPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of AgilhuPruebaExperto objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of AgilhuPruebaExperto objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseAgilhuPruebaExpertoPeer:doSelectJoinAll:doSelectJoinAll') as $callable)
    {
      call_user_func($callable, 'BaseAgilhuPruebaExpertoPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		AgilhuPruebaExpertoPeer::addSelectColumns($c);
		$startcol2 = (AgilhuPruebaExpertoPeer::NUM_COLUMNS - AgilhuPruebaExpertoPeer::NUM_LAZY_LOAD_COLUMNS);

		AgilhuHistoriaUsuarioPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (AgilhuHistoriaUsuarioPeer::NUM_COLUMNS - AgilhuHistoriaUsuarioPeer::NUM_LAZY_LOAD_COLUMNS);

		AgilhuUsuarioPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (AgilhuUsuarioPeer::NUM_COLUMNS - AgilhuUsuarioPeer::NUM_LAZY_LOAD_COLUMNS);

		$c->addJoin(array(AgilhuPruebaExpertoPeer::HIS_ID_ASOCIADA,), array(AgilhuHistoriaUsuarioPeer::HIS_ID,), $join_behavior);
		$c->addJoin(array(AgilhuPruebaExpertoPeer::USU_EVALUADOR_ID,), array(AgilhuUsuarioPeer::USU_ID,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = AgilhuPruebaExpertoPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = AgilhuPruebaExpertoPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = AgilhuPruebaExpertoPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				AgilhuPruebaExpertoPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined AgilhuHistoriaUsuario rows

			$key2 = AgilhuHistoriaUsuarioPeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = AgilhuHistoriaUsuarioPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = AgilhuHistoriaUsuarioPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					AgilhuHistoriaUsuarioPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (AgilhuPruebaExperto) to the collection in $obj2 (AgilhuHistoriaUsuario)
				$obj2->addAgilhuPruebaExperto($obj1);
			} // if joined row not null

			// Add objects for joined AgilhuUsuario rows

			$key3 = AgilhuUsuarioPeer::getPrimaryKeyHashFromRow($row, $startcol3);
			if ($key3 !== null) {
				$obj3 = AgilhuUsuarioPeer::getInstanceFromPool($key3);
				if (!$obj3) {

					$omClass = AgilhuUsuarioPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					AgilhuUsuarioPeer::addInstanceToPool($obj3, $key3);
				} // if obj3 loaded

				// Add the $obj1 (AgilhuPruebaExperto) to the collection in $obj3 (AgilhuUsuario)
				$obj3->addAgilhuPruebaExperto($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related AgilhuHistoriaUsuario table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptAgilhuHistoriaUsuario(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AgilhuPruebaExpertoPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(AgilhuPruebaExpertoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(AgilhuPruebaExpertoPeer::USU_EVALUADOR_ID,), array(AgilhuUsuarioPeer::USU_ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseAgilhuPruebaExpertoPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseAgilhuPruebaExpertoPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related AgilhuUsuario table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptAgilhuUsuario(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			AgilhuPruebaExpertoPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(AgilhuPruebaExpertoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(AgilhuPruebaExpertoPeer::HIS_ID_ASOCIADA,), array(AgilhuHistoriaUsuarioPeer::HIS_ID,), $join_behavior);

    foreach (sfMixer::getCallables('BaseAgilhuPruebaExpertoPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseAgilhuPruebaExpertoPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of AgilhuPruebaExperto objects pre-filled with all related objects except AgilhuHistoriaUsuario.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of AgilhuPruebaExperto objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptAgilhuHistoriaUsuario(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseAgilhuPruebaExpertoPeer:doSelectJoinAllExcept:doSelectJoinAllExcept') as $callable)
    {
      call_user_func($callable, 'BaseAgilhuPruebaExpertoPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		AgilhuPruebaExpertoPeer::addSelectColumns($c);
		$startcol2 = (AgilhuPruebaExpertoPeer::NUM_COLUMNS - AgilhuPruebaExpertoPeer::NUM_LAZY_LOAD_COLUMNS);

		AgilhuUsuarioPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (AgilhuUsuarioPeer::NUM_COLUMNS - AgilhuUsuarioPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(AgilhuPruebaExpertoPeer::USU_EVALUADOR_ID,), array(AgilhuUsuarioPeer::USU_ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = AgilhuPruebaExpertoPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = AgilhuPruebaExpertoPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = AgilhuPruebaExpertoPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				AgilhuPruebaExpertoPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined AgilhuUsuario rows

				$key2 = AgilhuUsuarioPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = AgilhuUsuarioPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = AgilhuUsuarioPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					AgilhuUsuarioPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (AgilhuPruebaExperto) to the collection in $obj2 (AgilhuUsuario)
				$obj2->addAgilhuPruebaExperto($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of AgilhuPruebaExperto objects pre-filled with all related objects except AgilhuUsuario.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of AgilhuPruebaExperto objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptAgilhuUsuario(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		AgilhuPruebaExpertoPeer::addSelectColumns($c);
		$startcol2 = (AgilhuPruebaExpertoPeer::NUM_COLUMNS - AgilhuPruebaExpertoPeer::NUM_LAZY_LOAD_COLUMNS);

		AgilhuHistoriaUsuarioPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (AgilhuHistoriaUsuarioPeer::NUM_COLUMNS - AgilhuHistoriaUsuarioPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(AgilhuPruebaExpertoPeer::HIS_ID_ASOCIADA,), array(AgilhuHistoriaUsuarioPeer::HIS_ID,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = AgilhuPruebaExpertoPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = AgilhuPruebaExpertoPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = AgilhuPruebaExpertoPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				AgilhuPruebaExpertoPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined AgilhuHistoriaUsuario rows

				$key2 = AgilhuHistoriaUsuarioPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = AgilhuHistoriaUsuarioPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = AgilhuHistoriaUsuarioPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					AgilhuHistoriaUsuarioPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (AgilhuPruebaExperto) to the collection in $obj2 (AgilhuHistoriaUsuario)
				$obj2->addAgilhuPruebaExperto($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return AgilhuPruebaExpertoPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a AgilhuPruebaExperto or Criteria object.
	 *
	 * @param      mixed $values Criteria or AgilhuPruebaExperto object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseAgilhuPruebaExpertoPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseAgilhuPruebaExpertoPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(AgilhuPruebaExpertoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from AgilhuPruebaExperto object
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseAgilhuPruebaExpertoPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseAgilhuPruebaExpertoPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a AgilhuPruebaExperto or Criteria object.
	 *
	 * @param      mixed $values Criteria or AgilhuPruebaExperto object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseAgilhuPruebaExpertoPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseAgilhuPruebaExpertoPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(AgilhuPruebaExpertoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(AgilhuPruebaExpertoPeer::PRU_FECHA_EVALUCION);
			$selectCriteria->add(AgilhuPruebaExpertoPeer::PRU_FECHA_EVALUCION, $criteria->remove(AgilhuPruebaExpertoPeer::PRU_FECHA_EVALUCION), $comparison);

			$comparison = $criteria->getComparison(AgilhuPruebaExpertoPeer::HIS_ID_ASOCIADA);
			$selectCriteria->add(AgilhuPruebaExpertoPeer::HIS_ID_ASOCIADA, $criteria->remove(AgilhuPruebaExpertoPeer::HIS_ID_ASOCIADA), $comparison);

			$comparison = $criteria->getComparison(AgilhuPruebaExpertoPeer::USU_EVALUADOR_ID);
			$selectCriteria->add(AgilhuPruebaExpertoPeer::USU_EVALUADOR_ID, $criteria->remove(AgilhuPruebaExpertoPeer::USU_EVALUADOR_ID), $comparison);

		} else { // $values is AgilhuPruebaExperto object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseAgilhuPruebaExpertoPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseAgilhuPruebaExpertoPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the agilhu_prueba_experto table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(AgilhuPruebaExpertoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(AgilhuPruebaExpertoPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a AgilhuPruebaExperto or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or AgilhuPruebaExperto object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(AgilhuPruebaExpertoPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			AgilhuPruebaExpertoPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof AgilhuPruebaExperto) {
			// invalidate the cache for this single object
			AgilhuPruebaExpertoPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			// primary key is composite; we therefore, expect
			// the primary key passed to be an array of pkey
			// values
			if (count($values) == count($values, COUNT_RECURSIVE)) {
				// array is not multi-dimensional
				$values = array($values);
			}

			foreach ($values as $value) {

				$criterion = $criteria->getNewCriterion(AgilhuPruebaExpertoPeer::PRU_FECHA_EVALUCION, $value[0]);
				$criterion->addAnd($criteria->getNewCriterion(AgilhuPruebaExpertoPeer::HIS_ID_ASOCIADA, $value[1]));
				$criterion->addAnd($criteria->getNewCriterion(AgilhuPruebaExpertoPeer::USU_EVALUADOR_ID, $value[2]));
				$criteria->addOr($criterion);

				// we can invalidate the cache for this single PK
				AgilhuPruebaExpertoPeer::removeInstanceFromPool($value);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given AgilhuPruebaExperto object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      AgilhuPruebaExperto $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(AgilhuPruebaExperto $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(AgilhuPruebaExpertoPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(AgilhuPruebaExpertoPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(AgilhuPruebaExpertoPeer::DATABASE_NAME, AgilhuPruebaExpertoPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = AgilhuPruebaExpertoPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve object using using composite pkey values.
	 * @param      string $pru_fecha_evalucion
	   @param      int $his_id_asociada
	   @param      int $usu_evaluador_id
	   
	 * @param      PropelPDO $con
	 * @return     AgilhuPruebaExperto
	 */
	public static function retrieveByPK($pru_fecha_evalucion, $his_id_asociada, $usu_evaluador_id, PropelPDO $con = null) {
		$key = serialize(array((string) $pru_fecha_evalucion, (string) $his_id_asociada, (string) $usu_evaluador_id));
 		if (null !== ($obj = AgilhuPruebaExpertoPeer::getInstanceFromPool($key))) {
 			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(AgilhuPruebaExpertoPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		$criteria = new Criteria(AgilhuPruebaExpertoPeer::DATABASE_NAME);
		$criteria->add(AgilhuPruebaExpertoPeer::PRU_FECHA_EVALUCION, $pru_fecha_evalucion);
		$criteria->add(AgilhuPruebaExpertoPeer::HIS_ID_ASOCIADA, $his_id_asociada);
		$criteria->add(AgilhuPruebaExpertoPeer::USU_EVALUADOR_ID, $usu_evaluador_id);
		$v = AgilhuPruebaExpertoPeer::doSelect($criteria, $con);

		return !empty($v) ? $v[0] : null;
	}
} // BaseAgilhuPruebaExpertoPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the AgilhuPruebaExpertoPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the AgilhuPruebaExpertoPeer class:
//
// Propel::getDatabaseMap(AgilhuPruebaExpertoPeer::DATABASE_NAME)->addTableBuilder(AgilhuPruebaExpertoPeer::TABLE_NAME, AgilhuPruebaExpertoPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseAgilhuPruebaExpertoPeer::DATABASE_NAME)->addTableBuilder(BaseAgilhuPruebaExpertoPeer::TABLE_NAME, BaseAgilhuPruebaExpertoPeer::getMapBuilder());

