<?php

/**
 * Base class that represents a row from the 'agilhu_historia_usuario' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Aug 30 10:19:33 2010
 *
 * @package    lib.model.om
 */
abstract class BaseAgilhuHistoriaUsuario extends BaseObject  implements Persistent {


  const PEER = 'AgilhuHistoriaUsuarioPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        AgilhuHistoriaUsuarioPeer
	 */
	protected static $peer;

	/**
	 * The value for the his_id field.
	 * @var        int
	 */
	protected $his_id;

	/**
	 * The value for the mod_id field.
	 * @var        int
	 */
	protected $mod_id;

	/**
	 * The value for the pro_id field.
	 * @var        int
	 */
	protected $pro_id;

	/**
	 * The value for the his_nombre field.
	 * @var        string
	 */
	protected $his_nombre;

	/**
	 * The value for the his_dependencias field.
	 * @var        string
	 */
	protected $his_dependencias;

	/**
	 * The value for the his_prioridad field.
	 * @var        string
	 */
	protected $his_prioridad;

	/**
	 * The value for the his_riesgo field.
	 * @var        int
	 */
	protected $his_riesgo;

	/**
	 * The value for the his_tiempo_estimado field.
	 * @var        int
	 */
	protected $his_tiempo_estimado;

	/**
	 * The value for the his_tiempo_real field.
	 * @var        int
	 */
	protected $his_tiempo_real;

	/**
	 * The value for the his_tipo_actividad field.
	 * @var        string
	 */
	protected $his_tipo_actividad;

	/**
	 * The value for the his_descripcion field.
	 * @var        string
	 */
	protected $his_descripcion;

	/**
	 * The value for the his_observaciones field.
	 * @var        string
	 */
	protected $his_observaciones;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the his_creador field.
	 * @var        string
	 */
	protected $his_creador;

	/**
	 * The value for the his_temporal field.
	 * @var        string
	 */
	protected $his_temporal;

	/**
	 * The value for the his_version field.
	 * @var        string
	 */
	protected $his_version;

	/**
	 * The value for the his_responsable field.
	 * @var        string
	 */
	protected $his_responsable;

	/**
	 * The value for the his_unidad_tiempo field.
	 * @var        string
	 */
	protected $his_unidad_tiempo;

	/**
	 * The value for the his_mensaje_version field.
	 * @var        string
	 */
	protected $his_mensaje_version;

	/**
	 * The value for the his_identificador_historia field.
	 * @var        int
	 */
	protected $his_identificador_historia;

	/**
	 * The value for the his_actor field.
	 * @var        string
	 */
	protected $his_actor;

	/**
	 * The value for the his_iteracion field.
	 * @var        int
	 */
	protected $his_iteracion;

	/**
	 * @var        AgilhuModulo
	 */
	protected $aAgilhuModulo;

	/**
	 * @var        AgilhuProyecto
	 */
	protected $aAgilhuProyecto;

	/**
	 * @var        array AgilhuPruebaExperto[] Collection to store aggregation of AgilhuPruebaExperto objects.
	 */
	protected $collAgilhuPruebaExpertos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAgilhuPruebaExpertos.
	 */
	private $lastAgilhuPruebaExpertoCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseAgilhuHistoriaUsuario object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [his_id] column value.
	 * 
	 * @return     int
	 */
	public function getHisId()
	{
		return $this->his_id;
	}

	/**
	 * Get the [mod_id] column value.
	 * 
	 * @return     int
	 */
	public function getModId()
	{
		return $this->mod_id;
	}

	/**
	 * Get the [pro_id] column value.
	 * 
	 * @return     int
	 */
	public function getProId()
	{
		return $this->pro_id;
	}

	/**
	 * Get the [his_nombre] column value.
	 * 
	 * @return     string
	 */
	public function getHisNombre()
	{
		return $this->his_nombre;
	}

	/**
	 * Get the [his_dependencias] column value.
	 * 
	 * @return     string
	 */
	public function getHisDependencias()
	{
		return $this->his_dependencias;
	}

	/**
	 * Get the [his_prioridad] column value.
	 * 
	 * @return     string
	 */
	public function getHisPrioridad()
	{
		return $this->his_prioridad;
	}

	/**
	 * Get the [his_riesgo] column value.
	 * 
	 * @return     int
	 */
	public function getHisRiesgo()
	{
		return $this->his_riesgo;
	}

	/**
	 * Get the [his_tiempo_estimado] column value.
	 * 
	 * @return     int
	 */
	public function getHisTiempoEstimado()
	{
		return $this->his_tiempo_estimado;
	}

	/**
	 * Get the [his_tiempo_real] column value.
	 * 
	 * @return     int
	 */
	public function getHisTiempoReal()
	{
		return $this->his_tiempo_real;
	}

	/**
	 * Get the [his_tipo_actividad] column value.
	 * 
	 * @return     string
	 */
	public function getHisTipoActividad()
	{
		return $this->his_tipo_actividad;
	}

	/**
	 * Get the [his_descripcion] column value.
	 * 
	 * @return     string
	 */
	public function getHisDescripcion()
	{
		return $this->his_descripcion;
	}

	/**
	 * Get the [his_observaciones] column value.
	 * 
	 * @return     string
	 */
	public function getHisObservaciones()
	{
		return $this->his_observaciones;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->created_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}



		try {
			$dt = new DateTime($this->updated_at);
		} catch (Exception $x) {
			throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [his_creador] column value.
	 * 
	 * @return     string
	 */
	public function getHisCreador()
	{
		return $this->his_creador;
	}

	/**
	 * Get the [his_temporal] column value.
	 * 
	 * @return     string
	 */
	public function getHisTemporal()
	{
		return $this->his_temporal;
	}

	/**
	 * Get the [his_version] column value.
	 * 
	 * @return     string
	 */
	public function getHisVersion()
	{
		return $this->his_version;
	}

	/**
	 * Get the [his_responsable] column value.
	 * 
	 * @return     string
	 */
	public function getHisResponsable()
	{
		return $this->his_responsable;
	}

	/**
	 * Get the [his_unidad_tiempo] column value.
	 * 
	 * @return     string
	 */
	public function getHisUnidadTiempo()
	{
		return $this->his_unidad_tiempo;
	}

	/**
	 * Get the [his_mensaje_version] column value.
	 * 
	 * @return     string
	 */
	public function getHisMensajeVersion()
	{
		return $this->his_mensaje_version;
	}

	/**
	 * Get the [his_identificador_historia] column value.
	 * 
	 * @return     int
	 */
	public function getHisIdentificadorHistoria()
	{
		return $this->his_identificador_historia;
	}

	/**
	 * Get the [his_actor] column value.
	 * 
	 * @return     string
	 */
	public function getHisActor()
	{
		return $this->his_actor;
	}

	/**
	 * Get the [his_iteracion] column value.
	 * 
	 * @return     int
	 */
	public function getHisIteracion()
	{
		return $this->his_iteracion;
	}

	/**
	 * Set the value of [his_id] column.
	 * 
	 * @param      int $v new value
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 */
	public function setHisId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->his_id !== $v) {
			$this->his_id = $v;
			$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::HIS_ID;
		}

		return $this;
	} // setHisId()

	/**
	 * Set the value of [mod_id] column.
	 * 
	 * @param      int $v new value
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 */
	public function setModId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->mod_id !== $v) {
			$this->mod_id = $v;
			$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::MOD_ID;
		}

		if ($this->aAgilhuModulo !== null && $this->aAgilhuModulo->getModId() !== $v) {
			$this->aAgilhuModulo = null;
		}

		return $this;
	} // setModId()

	/**
	 * Set the value of [pro_id] column.
	 * 
	 * @param      int $v new value
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 */
	public function setProId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->pro_id !== $v) {
			$this->pro_id = $v;
			$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::PRO_ID;
		}

		if ($this->aAgilhuProyecto !== null && $this->aAgilhuProyecto->getProId() !== $v) {
			$this->aAgilhuProyecto = null;
		}

		return $this;
	} // setProId()

	/**
	 * Set the value of [his_nombre] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 */
	public function setHisNombre($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->his_nombre !== $v) {
			$this->his_nombre = $v;
			$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::HIS_NOMBRE;
		}

		return $this;
	} // setHisNombre()

	/**
	 * Set the value of [his_dependencias] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 */
	public function setHisDependencias($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->his_dependencias !== $v) {
			$this->his_dependencias = $v;
			$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::HIS_DEPENDENCIAS;
		}

		return $this;
	} // setHisDependencias()

	/**
	 * Set the value of [his_prioridad] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 */
	public function setHisPrioridad($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->his_prioridad !== $v) {
			$this->his_prioridad = $v;
			$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::HIS_PRIORIDAD;
		}

		return $this;
	} // setHisPrioridad()

	/**
	 * Set the value of [his_riesgo] column.
	 * 
	 * @param      int $v new value
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 */
	public function setHisRiesgo($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->his_riesgo !== $v) {
			$this->his_riesgo = $v;
			$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::HIS_RIESGO;
		}

		return $this;
	} // setHisRiesgo()

	/**
	 * Set the value of [his_tiempo_estimado] column.
	 * 
	 * @param      int $v new value
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 */
	public function setHisTiempoEstimado($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->his_tiempo_estimado !== $v) {
			$this->his_tiempo_estimado = $v;
			$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::HIS_TIEMPO_ESTIMADO;
		}

		return $this;
	} // setHisTiempoEstimado()

	/**
	 * Set the value of [his_tiempo_real] column.
	 * 
	 * @param      int $v new value
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 */
	public function setHisTiempoReal($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->his_tiempo_real !== $v) {
			$this->his_tiempo_real = $v;
			$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::HIS_TIEMPO_REAL;
		}

		return $this;
	} // setHisTiempoReal()

	/**
	 * Set the value of [his_tipo_actividad] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 */
	public function setHisTipoActividad($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->his_tipo_actividad !== $v) {
			$this->his_tipo_actividad = $v;
			$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::HIS_TIPO_ACTIVIDAD;
		}

		return $this;
	} // setHisTipoActividad()

	/**
	 * Set the value of [his_descripcion] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 */
	public function setHisDescripcion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->his_descripcion !== $v) {
			$this->his_descripcion = $v;
			$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::HIS_DESCRIPCION;
		}

		return $this;
	} // setHisDescripcion()

	/**
	 * Set the value of [his_observaciones] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 */
	public function setHisObservaciones($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->his_observaciones !== $v) {
			$this->his_observaciones = $v;
			$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::HIS_OBSERVACIONES;
		}

		return $this;
	} // setHisObservaciones()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d\\TH:i:sO') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d\\TH:i:sO') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d\\TH:i:sO') : null);
				$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Set the value of [his_creador] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 */
	public function setHisCreador($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->his_creador !== $v) {
			$this->his_creador = $v;
			$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::HIS_CREADOR;
		}

		return $this;
	} // setHisCreador()

	/**
	 * Set the value of [his_temporal] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 */
	public function setHisTemporal($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->his_temporal !== $v) {
			$this->his_temporal = $v;
			$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::HIS_TEMPORAL;
		}

		return $this;
	} // setHisTemporal()

	/**
	 * Set the value of [his_version] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 */
	public function setHisVersion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->his_version !== $v) {
			$this->his_version = $v;
			$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::HIS_VERSION;
		}

		return $this;
	} // setHisVersion()

	/**
	 * Set the value of [his_responsable] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 */
	public function setHisResponsable($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->his_responsable !== $v) {
			$this->his_responsable = $v;
			$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::HIS_RESPONSABLE;
		}

		return $this;
	} // setHisResponsable()

	/**
	 * Set the value of [his_unidad_tiempo] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 */
	public function setHisUnidadTiempo($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->his_unidad_tiempo !== $v) {
			$this->his_unidad_tiempo = $v;
			$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::HIS_UNIDAD_TIEMPO;
		}

		return $this;
	} // setHisUnidadTiempo()

	/**
	 * Set the value of [his_mensaje_version] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 */
	public function setHisMensajeVersion($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->his_mensaje_version !== $v) {
			$this->his_mensaje_version = $v;
			$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::HIS_MENSAJE_VERSION;
		}

		return $this;
	} // setHisMensajeVersion()

	/**
	 * Set the value of [his_identificador_historia] column.
	 * 
	 * @param      int $v new value
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 */
	public function setHisIdentificadorHistoria($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->his_identificador_historia !== $v) {
			$this->his_identificador_historia = $v;
			$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::HIS_IDENTIFICADOR_HISTORIA;
		}

		return $this;
	} // setHisIdentificadorHistoria()

	/**
	 * Set the value of [his_actor] column.
	 * 
	 * @param      string $v new value
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 */
	public function setHisActor($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->his_actor !== $v) {
			$this->his_actor = $v;
			$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::HIS_ACTOR;
		}

		return $this;
	} // setHisActor()

	/**
	 * Set the value of [his_iteracion] column.
	 * 
	 * @param      int $v new value
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 */
	public function setHisIteracion($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->his_iteracion !== $v) {
			$this->his_iteracion = $v;
			$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::HIS_ITERACION;
		}

		return $this;
	} // setHisIteracion()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->his_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->mod_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->pro_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->his_nombre = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->his_dependencias = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->his_prioridad = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->his_riesgo = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->his_tiempo_estimado = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->his_tiempo_real = ($row[$startcol + 8] !== null) ? (int) $row[$startcol + 8] : null;
			$this->his_tipo_actividad = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->his_descripcion = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->his_observaciones = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->created_at = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->updated_at = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->his_creador = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->his_temporal = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->his_version = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->his_responsable = ($row[$startcol + 17] !== null) ? (string) $row[$startcol + 17] : null;
			$this->his_unidad_tiempo = ($row[$startcol + 18] !== null) ? (string) $row[$startcol + 18] : null;
			$this->his_mensaje_version = ($row[$startcol + 19] !== null) ? (string) $row[$startcol + 19] : null;
			$this->his_identificador_historia = ($row[$startcol + 20] !== null) ? (int) $row[$startcol + 20] : null;
			$this->his_actor = ($row[$startcol + 21] !== null) ? (string) $row[$startcol + 21] : null;
			$this->his_iteracion = ($row[$startcol + 22] !== null) ? (int) $row[$startcol + 22] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 23; // 23 = AgilhuHistoriaUsuarioPeer::NUM_COLUMNS - AgilhuHistoriaUsuarioPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating AgilhuHistoriaUsuario object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aAgilhuModulo !== null && $this->mod_id !== $this->aAgilhuModulo->getModId()) {
			$this->aAgilhuModulo = null;
		}
		if ($this->aAgilhuProyecto !== null && $this->pro_id !== $this->aAgilhuProyecto->getProId()) {
			$this->aAgilhuProyecto = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AgilhuHistoriaUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = AgilhuHistoriaUsuarioPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aAgilhuModulo = null;
			$this->aAgilhuProyecto = null;
			$this->collAgilhuPruebaExpertos = null;
			$this->lastAgilhuPruebaExpertoCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseAgilhuHistoriaUsuario:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AgilhuHistoriaUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			AgilhuHistoriaUsuarioPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseAgilhuHistoriaUsuario:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseAgilhuHistoriaUsuario:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(AgilhuHistoriaUsuarioPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

    if ($this->isModified() && !$this->isColumnModified(AgilhuHistoriaUsuarioPeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AgilhuHistoriaUsuarioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseAgilhuHistoriaUsuario:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			AgilhuHistoriaUsuarioPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aAgilhuModulo !== null) {
				if ($this->aAgilhuModulo->isModified() || $this->aAgilhuModulo->isNew()) {
					$affectedRows += $this->aAgilhuModulo->save($con);
				}
				$this->setAgilhuModulo($this->aAgilhuModulo);
			}

			if ($this->aAgilhuProyecto !== null) {
				if ($this->aAgilhuProyecto->isModified() || $this->aAgilhuProyecto->isNew()) {
					$affectedRows += $this->aAgilhuProyecto->save($con);
				}
				$this->setAgilhuProyecto($this->aAgilhuProyecto);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = AgilhuHistoriaUsuarioPeer::HIS_ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = AgilhuHistoriaUsuarioPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setHisId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += AgilhuHistoriaUsuarioPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collAgilhuPruebaExpertos !== null) {
				foreach ($this->collAgilhuPruebaExpertos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aAgilhuModulo !== null) {
				if (!$this->aAgilhuModulo->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aAgilhuModulo->getValidationFailures());
				}
			}

			if ($this->aAgilhuProyecto !== null) {
				if (!$this->aAgilhuProyecto->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aAgilhuProyecto->getValidationFailures());
				}
			}


			if (($retval = AgilhuHistoriaUsuarioPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collAgilhuPruebaExpertos !== null) {
					foreach ($this->collAgilhuPruebaExpertos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AgilhuHistoriaUsuarioPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getHisId();
				break;
			case 1:
				return $this->getModId();
				break;
			case 2:
				return $this->getProId();
				break;
			case 3:
				return $this->getHisNombre();
				break;
			case 4:
				return $this->getHisDependencias();
				break;
			case 5:
				return $this->getHisPrioridad();
				break;
			case 6:
				return $this->getHisRiesgo();
				break;
			case 7:
				return $this->getHisTiempoEstimado();
				break;
			case 8:
				return $this->getHisTiempoReal();
				break;
			case 9:
				return $this->getHisTipoActividad();
				break;
			case 10:
				return $this->getHisDescripcion();
				break;
			case 11:
				return $this->getHisObservaciones();
				break;
			case 12:
				return $this->getCreatedAt();
				break;
			case 13:
				return $this->getUpdatedAt();
				break;
			case 14:
				return $this->getHisCreador();
				break;
			case 15:
				return $this->getHisTemporal();
				break;
			case 16:
				return $this->getHisVersion();
				break;
			case 17:
				return $this->getHisResponsable();
				break;
			case 18:
				return $this->getHisUnidadTiempo();
				break;
			case 19:
				return $this->getHisMensajeVersion();
				break;
			case 20:
				return $this->getHisIdentificadorHistoria();
				break;
			case 21:
				return $this->getHisActor();
				break;
			case 22:
				return $this->getHisIteracion();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = AgilhuHistoriaUsuarioPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getHisId(),
			$keys[1] => $this->getModId(),
			$keys[2] => $this->getProId(),
			$keys[3] => $this->getHisNombre(),
			$keys[4] => $this->getHisDependencias(),
			$keys[5] => $this->getHisPrioridad(),
			$keys[6] => $this->getHisRiesgo(),
			$keys[7] => $this->getHisTiempoEstimado(),
			$keys[8] => $this->getHisTiempoReal(),
			$keys[9] => $this->getHisTipoActividad(),
			$keys[10] => $this->getHisDescripcion(),
			$keys[11] => $this->getHisObservaciones(),
			$keys[12] => $this->getCreatedAt(),
			$keys[13] => $this->getUpdatedAt(),
			$keys[14] => $this->getHisCreador(),
			$keys[15] => $this->getHisTemporal(),
			$keys[16] => $this->getHisVersion(),
			$keys[17] => $this->getHisResponsable(),
			$keys[18] => $this->getHisUnidadTiempo(),
			$keys[19] => $this->getHisMensajeVersion(),
			$keys[20] => $this->getHisIdentificadorHistoria(),
			$keys[21] => $this->getHisActor(),
			$keys[22] => $this->getHisIteracion(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AgilhuHistoriaUsuarioPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setHisId($value);
				break;
			case 1:
				$this->setModId($value);
				break;
			case 2:
				$this->setProId($value);
				break;
			case 3:
				$this->setHisNombre($value);
				break;
			case 4:
				$this->setHisDependencias($value);
				break;
			case 5:
				$this->setHisPrioridad($value);
				break;
			case 6:
				$this->setHisRiesgo($value);
				break;
			case 7:
				$this->setHisTiempoEstimado($value);
				break;
			case 8:
				$this->setHisTiempoReal($value);
				break;
			case 9:
				$this->setHisTipoActividad($value);
				break;
			case 10:
				$this->setHisDescripcion($value);
				break;
			case 11:
				$this->setHisObservaciones($value);
				break;
			case 12:
				$this->setCreatedAt($value);
				break;
			case 13:
				$this->setUpdatedAt($value);
				break;
			case 14:
				$this->setHisCreador($value);
				break;
			case 15:
				$this->setHisTemporal($value);
				break;
			case 16:
				$this->setHisVersion($value);
				break;
			case 17:
				$this->setHisResponsable($value);
				break;
			case 18:
				$this->setHisUnidadTiempo($value);
				break;
			case 19:
				$this->setHisMensajeVersion($value);
				break;
			case 20:
				$this->setHisIdentificadorHistoria($value);
				break;
			case 21:
				$this->setHisActor($value);
				break;
			case 22:
				$this->setHisIteracion($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = AgilhuHistoriaUsuarioPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setHisId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setModId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setProId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setHisNombre($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setHisDependencias($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setHisPrioridad($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setHisRiesgo($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setHisTiempoEstimado($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setHisTiempoReal($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setHisTipoActividad($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setHisDescripcion($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setHisObservaciones($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setCreatedAt($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setUpdatedAt($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setHisCreador($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setHisTemporal($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setHisVersion($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setHisResponsable($arr[$keys[17]]);
		if (array_key_exists($keys[18], $arr)) $this->setHisUnidadTiempo($arr[$keys[18]]);
		if (array_key_exists($keys[19], $arr)) $this->setHisMensajeVersion($arr[$keys[19]]);
		if (array_key_exists($keys[20], $arr)) $this->setHisIdentificadorHistoria($arr[$keys[20]]);
		if (array_key_exists($keys[21], $arr)) $this->setHisActor($arr[$keys[21]]);
		if (array_key_exists($keys[22], $arr)) $this->setHisIteracion($arr[$keys[22]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(AgilhuHistoriaUsuarioPeer::DATABASE_NAME);

		if ($this->isColumnModified(AgilhuHistoriaUsuarioPeer::HIS_ID)) $criteria->add(AgilhuHistoriaUsuarioPeer::HIS_ID, $this->his_id);
		if ($this->isColumnModified(AgilhuHistoriaUsuarioPeer::MOD_ID)) $criteria->add(AgilhuHistoriaUsuarioPeer::MOD_ID, $this->mod_id);
		if ($this->isColumnModified(AgilhuHistoriaUsuarioPeer::PRO_ID)) $criteria->add(AgilhuHistoriaUsuarioPeer::PRO_ID, $this->pro_id);
		if ($this->isColumnModified(AgilhuHistoriaUsuarioPeer::HIS_NOMBRE)) $criteria->add(AgilhuHistoriaUsuarioPeer::HIS_NOMBRE, $this->his_nombre);
		if ($this->isColumnModified(AgilhuHistoriaUsuarioPeer::HIS_DEPENDENCIAS)) $criteria->add(AgilhuHistoriaUsuarioPeer::HIS_DEPENDENCIAS, $this->his_dependencias);
		if ($this->isColumnModified(AgilhuHistoriaUsuarioPeer::HIS_PRIORIDAD)) $criteria->add(AgilhuHistoriaUsuarioPeer::HIS_PRIORIDAD, $this->his_prioridad);
		if ($this->isColumnModified(AgilhuHistoriaUsuarioPeer::HIS_RIESGO)) $criteria->add(AgilhuHistoriaUsuarioPeer::HIS_RIESGO, $this->his_riesgo);
		if ($this->isColumnModified(AgilhuHistoriaUsuarioPeer::HIS_TIEMPO_ESTIMADO)) $criteria->add(AgilhuHistoriaUsuarioPeer::HIS_TIEMPO_ESTIMADO, $this->his_tiempo_estimado);
		if ($this->isColumnModified(AgilhuHistoriaUsuarioPeer::HIS_TIEMPO_REAL)) $criteria->add(AgilhuHistoriaUsuarioPeer::HIS_TIEMPO_REAL, $this->his_tiempo_real);
		if ($this->isColumnModified(AgilhuHistoriaUsuarioPeer::HIS_TIPO_ACTIVIDAD)) $criteria->add(AgilhuHistoriaUsuarioPeer::HIS_TIPO_ACTIVIDAD, $this->his_tipo_actividad);
		if ($this->isColumnModified(AgilhuHistoriaUsuarioPeer::HIS_DESCRIPCION)) $criteria->add(AgilhuHistoriaUsuarioPeer::HIS_DESCRIPCION, $this->his_descripcion);
		if ($this->isColumnModified(AgilhuHistoriaUsuarioPeer::HIS_OBSERVACIONES)) $criteria->add(AgilhuHistoriaUsuarioPeer::HIS_OBSERVACIONES, $this->his_observaciones);
		if ($this->isColumnModified(AgilhuHistoriaUsuarioPeer::CREATED_AT)) $criteria->add(AgilhuHistoriaUsuarioPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(AgilhuHistoriaUsuarioPeer::UPDATED_AT)) $criteria->add(AgilhuHistoriaUsuarioPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(AgilhuHistoriaUsuarioPeer::HIS_CREADOR)) $criteria->add(AgilhuHistoriaUsuarioPeer::HIS_CREADOR, $this->his_creador);
		if ($this->isColumnModified(AgilhuHistoriaUsuarioPeer::HIS_TEMPORAL)) $criteria->add(AgilhuHistoriaUsuarioPeer::HIS_TEMPORAL, $this->his_temporal);
		if ($this->isColumnModified(AgilhuHistoriaUsuarioPeer::HIS_VERSION)) $criteria->add(AgilhuHistoriaUsuarioPeer::HIS_VERSION, $this->his_version);
		if ($this->isColumnModified(AgilhuHistoriaUsuarioPeer::HIS_RESPONSABLE)) $criteria->add(AgilhuHistoriaUsuarioPeer::HIS_RESPONSABLE, $this->his_responsable);
		if ($this->isColumnModified(AgilhuHistoriaUsuarioPeer::HIS_UNIDAD_TIEMPO)) $criteria->add(AgilhuHistoriaUsuarioPeer::HIS_UNIDAD_TIEMPO, $this->his_unidad_tiempo);
		if ($this->isColumnModified(AgilhuHistoriaUsuarioPeer::HIS_MENSAJE_VERSION)) $criteria->add(AgilhuHistoriaUsuarioPeer::HIS_MENSAJE_VERSION, $this->his_mensaje_version);
		if ($this->isColumnModified(AgilhuHistoriaUsuarioPeer::HIS_IDENTIFICADOR_HISTORIA)) $criteria->add(AgilhuHistoriaUsuarioPeer::HIS_IDENTIFICADOR_HISTORIA, $this->his_identificador_historia);
		if ($this->isColumnModified(AgilhuHistoriaUsuarioPeer::HIS_ACTOR)) $criteria->add(AgilhuHistoriaUsuarioPeer::HIS_ACTOR, $this->his_actor);
		if ($this->isColumnModified(AgilhuHistoriaUsuarioPeer::HIS_ITERACION)) $criteria->add(AgilhuHistoriaUsuarioPeer::HIS_ITERACION, $this->his_iteracion);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(AgilhuHistoriaUsuarioPeer::DATABASE_NAME);

		$criteria->add(AgilhuHistoriaUsuarioPeer::HIS_ID, $this->his_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getHisId();
	}

	/**
	 * Generic method to set the primary key (his_id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setHisId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of AgilhuHistoriaUsuario (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setModId($this->mod_id);

		$copyObj->setProId($this->pro_id);

		$copyObj->setHisNombre($this->his_nombre);

		$copyObj->setHisDependencias($this->his_dependencias);

		$copyObj->setHisPrioridad($this->his_prioridad);

		$copyObj->setHisRiesgo($this->his_riesgo);

		$copyObj->setHisTiempoEstimado($this->his_tiempo_estimado);

		$copyObj->setHisTiempoReal($this->his_tiempo_real);

		$copyObj->setHisTipoActividad($this->his_tipo_actividad);

		$copyObj->setHisDescripcion($this->his_descripcion);

		$copyObj->setHisObservaciones($this->his_observaciones);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setHisCreador($this->his_creador);

		$copyObj->setHisTemporal($this->his_temporal);

		$copyObj->setHisVersion($this->his_version);

		$copyObj->setHisResponsable($this->his_responsable);

		$copyObj->setHisUnidadTiempo($this->his_unidad_tiempo);

		$copyObj->setHisMensajeVersion($this->his_mensaje_version);

		$copyObj->setHisIdentificadorHistoria($this->his_identificador_historia);

		$copyObj->setHisActor($this->his_actor);

		$copyObj->setHisIteracion($this->his_iteracion);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getAgilhuPruebaExpertos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAgilhuPruebaExperto($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setHisId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     AgilhuHistoriaUsuario Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     AgilhuHistoriaUsuarioPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new AgilhuHistoriaUsuarioPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a AgilhuModulo object.
	 *
	 * @param      AgilhuModulo $v
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setAgilhuModulo(AgilhuModulo $v = null)
	{
		if ($v === null) {
			$this->setModId(NULL);
		} else {
			$this->setModId($v->getModId());
		}

		$this->aAgilhuModulo = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the AgilhuModulo object, it will not be re-added.
		if ($v !== null) {
			$v->addAgilhuHistoriaUsuario($this);
		}

		return $this;
	}


	/**
	 * Get the associated AgilhuModulo object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     AgilhuModulo The associated AgilhuModulo object.
	 * @throws     PropelException
	 */
	public function getAgilhuModulo(PropelPDO $con = null)
	{
		if ($this->aAgilhuModulo === null && ($this->mod_id !== null)) {
			$c = new Criteria(AgilhuModuloPeer::DATABASE_NAME);
			$c->add(AgilhuModuloPeer::MOD_ID, $this->mod_id);
			$this->aAgilhuModulo = AgilhuModuloPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aAgilhuModulo->addAgilhuHistoriaUsuarios($this);
			 */
		}
		return $this->aAgilhuModulo;
	}

	/**
	 * Declares an association between this object and a AgilhuProyecto object.
	 *
	 * @param      AgilhuProyecto $v
	 * @return     AgilhuHistoriaUsuario The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setAgilhuProyecto(AgilhuProyecto $v = null)
	{
		if ($v === null) {
			$this->setProId(NULL);
		} else {
			$this->setProId($v->getProId());
		}

		$this->aAgilhuProyecto = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the AgilhuProyecto object, it will not be re-added.
		if ($v !== null) {
			$v->addAgilhuHistoriaUsuario($this);
		}

		return $this;
	}


	/**
	 * Get the associated AgilhuProyecto object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     AgilhuProyecto The associated AgilhuProyecto object.
	 * @throws     PropelException
	 */
	public function getAgilhuProyecto(PropelPDO $con = null)
	{
		if ($this->aAgilhuProyecto === null && ($this->pro_id !== null)) {
			$c = new Criteria(AgilhuProyectoPeer::DATABASE_NAME);
			$c->add(AgilhuProyectoPeer::PRO_ID, $this->pro_id);
			$this->aAgilhuProyecto = AgilhuProyectoPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aAgilhuProyecto->addAgilhuHistoriaUsuarios($this);
			 */
		}
		return $this->aAgilhuProyecto;
	}

	/**
	 * Clears out the collAgilhuPruebaExpertos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAgilhuPruebaExpertos()
	 */
	public function clearAgilhuPruebaExpertos()
	{
		$this->collAgilhuPruebaExpertos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAgilhuPruebaExpertos collection (array).
	 *
	 * By default this just sets the collAgilhuPruebaExpertos collection to an empty array (like clearcollAgilhuPruebaExpertos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAgilhuPruebaExpertos()
	{
		$this->collAgilhuPruebaExpertos = array();
	}

	/**
	 * Gets an array of AgilhuPruebaExperto objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this AgilhuHistoriaUsuario has previously been saved, it will retrieve
	 * related AgilhuPruebaExpertos from storage. If this AgilhuHistoriaUsuario is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array AgilhuPruebaExperto[]
	 * @throws     PropelException
	 */
	public function getAgilhuPruebaExpertos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AgilhuHistoriaUsuarioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAgilhuPruebaExpertos === null) {
			if ($this->isNew()) {
			   $this->collAgilhuPruebaExpertos = array();
			} else {

				$criteria->add(AgilhuPruebaExpertoPeer::HIS_ID_ASOCIADA, $this->his_id);

				AgilhuPruebaExpertoPeer::addSelectColumns($criteria);
				$this->collAgilhuPruebaExpertos = AgilhuPruebaExpertoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AgilhuPruebaExpertoPeer::HIS_ID_ASOCIADA, $this->his_id);

				AgilhuPruebaExpertoPeer::addSelectColumns($criteria);
				if (!isset($this->lastAgilhuPruebaExpertoCriteria) || !$this->lastAgilhuPruebaExpertoCriteria->equals($criteria)) {
					$this->collAgilhuPruebaExpertos = AgilhuPruebaExpertoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAgilhuPruebaExpertoCriteria = $criteria;
		return $this->collAgilhuPruebaExpertos;
	}

	/**
	 * Returns the number of related AgilhuPruebaExperto objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related AgilhuPruebaExperto objects.
	 * @throws     PropelException
	 */
	public function countAgilhuPruebaExpertos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AgilhuHistoriaUsuarioPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAgilhuPruebaExpertos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AgilhuPruebaExpertoPeer::HIS_ID_ASOCIADA, $this->his_id);

				$count = AgilhuPruebaExpertoPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AgilhuPruebaExpertoPeer::HIS_ID_ASOCIADA, $this->his_id);

				if (!isset($this->lastAgilhuPruebaExpertoCriteria) || !$this->lastAgilhuPruebaExpertoCriteria->equals($criteria)) {
					$count = AgilhuPruebaExpertoPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collAgilhuPruebaExpertos);
				}
			} else {
				$count = count($this->collAgilhuPruebaExpertos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a AgilhuPruebaExperto object to this object
	 * through the AgilhuPruebaExperto foreign key attribute.
	 *
	 * @param      AgilhuPruebaExperto $l AgilhuPruebaExperto
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAgilhuPruebaExperto(AgilhuPruebaExperto $l)
	{
		if ($this->collAgilhuPruebaExpertos === null) {
			$this->initAgilhuPruebaExpertos();
		}
		if (!in_array($l, $this->collAgilhuPruebaExpertos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAgilhuPruebaExpertos, $l);
			$l->setAgilhuHistoriaUsuario($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this AgilhuHistoriaUsuario is new, it will return
	 * an empty collection; or if this AgilhuHistoriaUsuario has previously
	 * been saved, it will retrieve related AgilhuPruebaExpertos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in AgilhuHistoriaUsuario.
	 */
	public function getAgilhuPruebaExpertosJoinAgilhuUsuario($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AgilhuHistoriaUsuarioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAgilhuPruebaExpertos === null) {
			if ($this->isNew()) {
				$this->collAgilhuPruebaExpertos = array();
			} else {

				$criteria->add(AgilhuPruebaExpertoPeer::HIS_ID_ASOCIADA, $this->his_id);

				$this->collAgilhuPruebaExpertos = AgilhuPruebaExpertoPeer::doSelectJoinAgilhuUsuario($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(AgilhuPruebaExpertoPeer::HIS_ID_ASOCIADA, $this->his_id);

			if (!isset($this->lastAgilhuPruebaExpertoCriteria) || !$this->lastAgilhuPruebaExpertoCriteria->equals($criteria)) {
				$this->collAgilhuPruebaExpertos = AgilhuPruebaExpertoPeer::doSelectJoinAgilhuUsuario($criteria, $con, $join_behavior);
			}
		}
		$this->lastAgilhuPruebaExpertoCriteria = $criteria;

		return $this->collAgilhuPruebaExpertos;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collAgilhuPruebaExpertos) {
				foreach ((array) $this->collAgilhuPruebaExpertos as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collAgilhuPruebaExpertos = null;
			$this->aAgilhuModulo = null;
			$this->aAgilhuProyecto = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseAgilhuHistoriaUsuario:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseAgilhuHistoriaUsuario::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseAgilhuHistoriaUsuario
